### ISSUE TITLE
Android 4.1.2 could'nt scroll picker

### ISSUE THREAD

**Issue by Flywhiter** [gzu-liyujiang/AndroidPicker#1]
my huaiweic8815 rooted can't scroll picker to choose item
5.1 dont have this bug

**Comment by gzu-liyujiang** [comment]
2015.10.23, Fixed:
已修复，是因为多加了一个ScrollView来包裹，导致android2.*及android4.*滚动不了

**Comment by Flywhiter** [comment]
哈哈 速度好快啊

**Comment by Flywhiter** [comment]
还有个bug lib adapterhelper类 setchecked方法里面 Checkable view = retrieveView(viewId) 
Checkable并不是一个view右边返回view类型转换失败 我查看了checkbox继承CompoundButton改成这个就没问题了这个不知道是不是我jdk版本问题

**Comment by gzu-liyujiang** [comment]
@Flywhiter 使用Checkable，是因为我觉得CheckedTextView、CheckBox、CompoundButton都实现了Checkable。我只是考虑到方便CheckedTextView和CheckBox，未验证过CheckBox，用过CheckedTextView在项目中使用没报错，不知道是不是jdk版本问题。

**Comment by gzu-liyujiang** [comment]
@Flywhiter 把那个setChecked方法修改为：
```java
        if (view instanceof CompoundButton) {
            ((CompoundButton) view).setChecked(checked);
        } else if (view instanceof CheckedTextView) {
            ((CheckedTextView) view).setChecked(checked);
        }
```
