### ISSUE TITLE
没有年月日时分的picker

### ISSUE THREAD

**Issue by byjamesCN** [gzu-liyujiang/AndroidPicker#10]
年月日时分的picker用得比较多，请添加这个

**Comment by liyujiang-gzu** [comment]
可以的，请问你的使用场景是啥？？一般年月日和时分不是分开来选的么

**Comment by byjamesCN** [comment]
手机或平板上的各种管理系统
其它带有创建功能的APP也可能需要些功能
分开来选是可以，但是体验肯定是没有直接选好

**Comment by zhangfy068** [comment]
提个bug,DateTimePicker.setSelectedItem();方法中应该改成selectedHour = DateUtils.fillZero(hour); selectedMinute = DateUtils.fillZero(minute);否则传个位数会有bug.

**Comment by liyujiang-gzu** [comment]
@zhangfy068 的确，传个位数时不唯一

**Comment by yj970** [comment]
@liyujiang-gzu 我在看最新发版的1.2.1还是没解决DateTimePicker.setSelectedItem();selectedHour 传个位数会有bug这个问题，不知道有没时间改改呢~~

**Comment by liyujiang-gzu** [comment]
v1.2.3已解决
