### ISSUE TITLE
V4包每次都请求最新的版本，对低版本不兼容

### ISSUE THREAD

**Issue by guotaogithub** [gzu-liyujiang/AndroidPicker#103]
V4的包太新了，工程里用最新的版本会崩溃

**Comment by caocao123** [comment]
求解决

**Comment by liyujiang-gzu** [comment]
请将依赖改为以下类似的，排除v4包：
compile('cn.qqtheme.framework:WheelPicker:版本号') {
    exclude group: 'com.android.support'
}
