### ISSUE TITLE
setSelectItem

### ISSUE THREAD

**Issue by wengleipactera** [gzu-liyujiang/AndroidPicker#104]
我通过new NumberPicker  然后用addView（pick.getContentView) 来显示这个picker的  在picker已经显示的情况下，想通过picker.setSelectedIndex(mIndex);  改变当前选中的位置，为什么picker没有滚动到指定的mIndex位置

**Comment by zhouguangfu09** [comment]
已经显示的情况下的确更改失效，我也碰到了这个问题；

**Comment by wengleipactera** [comment]
我通过picker.getwheelview然后setselectindex去刷新picker  虽然ui改变了  但是会触发picker的onwheellistener  这不是我想要的


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：Guangfu Zhou <notifications@github.com>
时间：周四 4月6日 22:57
收件人：gzu-liyujiang/AndroidPicker <AndroidPicker@noreply.github.com>
抄送：wengleipactera <lei.weng@pactera.com>,Author <author@noreply.github.com>
主题：Re: [gzu-liyujiang/AndroidPicker] setSelectItem (#104)

**Comment by wengleipactera** [comment]
来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：Guangfu Zhou <notifications@github.com>
时间：周四 4月6日 22:57
收件人：gzu-liyujiang/AndroidPicker <AndroidPicker@noreply.github.com>
抄送：wengleipactera <lei.weng@pactera.com>,Author <author@noreply.github.com>
主题：Re: [gzu-liyujiang/AndroidPicker] setSelectItem (#104)

**Comment by zhouguangfu09** [comment]
"会触发picker的onwheellistener "，正常情况也应该是这样的； 怎么改变TimePicker的setselectindex呢

**Comment by wengleipactera** [comment]
目前没有好的办法 只能重新new picker ，用这个控件还需要自己做一些ui上的处理  ，还是比较麻烦的

**Comment by zhouguangfu09** [comment]
嗯，非常感谢及时解答:)

**Comment by liyujiang-gzu** [comment]
1.5.X版本对此有所改进

**Comment by liyujiang-gzu** [comment]
1.5.X版本已支持再次调用pciker.setData刷新数据
