### ISSUE TITLE
华为手机型号H30-T10,日期选择，地区选择会出现末尾省略号，滑动了就好了

### ISSUE THREAD

**Issue by zzzz1387** [gzu-liyujiang/AndroidPicker#106]
日期选择器打开后显示的部分只能显示年的前两位，后两位是省略号，上下滑动就好了，地区选择我用的是两级联动的，最左侧的也是后面是省略号，右侧的上半部分包括我默认选择的城市是完整显示，下半部分也是后面省略号，都是滑动到看不到，然后滑出来就好了

**Comment by liyujiang-gzu** [comment]
@zzzz1387 1.5.X版本应该已经不存在此问题了，没华为手机，待验证

**Comment by zzzz1387** [comment]
今天升到了1.5.2版本，这一款手机已经没有这种问题了
