### ISSUE TITLE
setAnimationStyle 没有效果

### ISSUE THREAD

**Issue by onionYJK** [gzu-liyujiang/AndroidPicker#110]
给picker设置动画
<style name="ActionSheetDialogAnimation" parent="@android:style/Animation.Dialog">
        <item name="android:windowEnterAnimation">@anim/actionsheet_dialog_in</item>
        <item name="android:windowExitAnimation">@anim/actionsheet_dialog_out</item>
    </style>
没有效果

**Comment by liyujiang-gzu** [comment]
没道理啊，demo里的第一个就是xml的动画，是有效果的。强烈建议你用ObjectAnimator来实现动画

**Comment by liyujiang-gzu** [comment]
你的anim文件需要使用android:windowEnterAnimation和android:windowExitAnimation才行：
```xml
  <style name="Animation.CustomPopup" parent="@android:style/Animation">
        <item name="android:windowEnterAnimation">@anim/popup_in</item>
        <item name="android:windowExitAnimation">@anim/popup_out</item>
    </style>
```

**Comment by onionYJK** [comment]
我就是用的这个，但是复制上来的时候不知道怎么变成那样了。
`<style name="ActionSheetDialogAnimation" parent="@android:style/Animation.Dialog">
        <item name="android:windowEnterAnimation">@anim/actionsheet_dialog_in</item>
        <item name="android:windowExitAnimation">@anim/actionsheet_dialog_out</item>
    </style>`

**Comment by onionYJK** [comment]
我仔细看了下效果，准确点应该是进入的动画是正确的，但是时间不对，进入动画的时间很长，然后退出动画是不对的，而且屏幕会闪一下，而且动画的时间不对，很慢。

**Comment by triplezhao** [comment]
我也遇到这个问题。

**Comment by liyujiang-gzu** [comment]
@triplezhao @onionYJK 1.5.2已去掉默认动画，可以自己通过pciker.getRootView()设置Animator，或者调用picker.setAnimationStyle()设置Animation
