### ISSUE TITLE
WheelPicker启动关闭太慢了

### ISSUE THREAD

**Issue by libin1993** [gzu-liyujiang/AndroidPicker#115]
动画能加个关闭方法吗

**Comment by liyujiang-gzu** [comment]
谢谢您的建议

**Comment by libin1993** [comment]
我把您的代码启动关闭动画注释掉了

**Comment by liyujiang-gzu** [comment]
1.5.2已去掉默认动画，可以自己通过pciker.getRootView()设置Animator，或者调用picker.setAnimationStyle()设置Animation
