### ISSUE TITLE
河南省信阳市负忧    负忧显示bug

### ISSUE THREAD

**Issue by libin1993** [gzu-liyujiang/AndroidPicker#119]

**Comment by liyujiang-gzu** [comment]
JSON数据的问题，“负忧”多了特殊字符，搜索修改assets/city.json文件删掉那个特殊空白符即可

**Comment by libin1993** [comment]
{
        "areaId": "411500",
        "areaName": "信阳市",
        "counties": [
          {
            "areaId": "411502",
            "areaName": "负忧"
          },
          {
            "areaId": "411503",
            "areaName": "平桥区"
          },
          
没有特殊空白符啊！

**Comment by libin1993** [comment]
没有特殊空白符啊

**Comment by liyujiang-gzu** [comment]
前两天我已经改了
