### ISSUE TITLE
混淆时候需要加入以下规则，测试通过，感谢作者解答

### ISSUE THREAD

**Issue by cellzer** [gzu-liyujiang/AndroidPicker#12]
```
-keep class cn.qqtheme.framework.entity.** { *;}
-keep class cn.qqtheme.framework.picker.AddressPickerr$* { *;}
```

**Comment by dinghongyan** [comment]
按照这个写法，编译报错

> FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: proguard.ParseException: Expecting java type before ';' in line 190 of file '....../app/proguard-project.txt'

大括号之内加个*就好了
-keep class cn.qqtheme.framework.entity.** { *;}
