### ISSUE TITLE
双项选择器设置默认选中项混乱Bug

### ISSUE THREAD

**Issue by Loyea** [gzu-liyujiang/AndroidPicker#122]
<img width="958" alt="qq20170609-151917 2x" src="https://user-images.githubusercontent.com/3928564/26965135-0859c6f2-4d27-11e7-85aa-3ff7c15acda5.png">

图中高亮的方法，设置为0，0的时候显示的两项都不是数据集的第一个，具体错在哪我没去看源代码，作者自己看看吧。

**Comment by liyujiang-gzu** [comment]
已修改WheelView.java的第175行：
```java
        if (**index == 0 ||** (index > 0 && index < size && index != selectedIndex)) {
            initPosition = index;
            totalScrollY = 0;//回归顶部，不然重设索引的话位置会偏移，就会显示出不对位置的数据
            offset = 0;
            invalidate();
        }
```
