### ISSUE TITLE
文件选择器能否添加调整item高度的接口

### ISSUE THREAD

**Issue by dinghongyan** [gzu-liyujiang/AndroidPicker#15]
文件选择器中，目前没有找到调整item高度的接口，用在平板上的时候，高度太小，字体也太小，目前只能修改源码，是否可以提供一套参数，修改item的高度、文字大小、颜色之类的

**Comment by liyujiang-gzu** [comment]
FilePicker.java里默认为setHalfScreen(true);设置半屏，可以调用setSizehse或tHeight再次设置高度

**Comment by liyujiang-gzu** [comment]
本来以前item所在的View我是用xml写的，后来在FileAdapter里的getView里改成android.R.layout.activity_list_item了。   你可以按你的思路改一下FileAdapter，使之暴露一个方法来设置。

**Comment by liyujiang-gzu** [comment]
可修改源代码的file_item.xml布局文件。#9e83d1251d754f6842dc43247f50bdcee06e9303
