### ISSUE TITLE
初始化选中第一项时字体的颜色不改变

### ISSUE THREAD

**Issue by MillerKevin** [gzu-liyujiang/AndroidPicker#16]
方法picker.setOffset(value) 当设置value的值大于等于2时，当对话框初始化显示时，第一项的颜色没有改变，和没有选中的颜色一样。

**Comment by yj970** [comment]
我也遇到了这个问题！

**Comment by liyujiang-gzu** [comment]
已修复，见issues#66，commits#83083be64dc40f1ba7565656ea5997e33d0ec755
