### ISSUE TITLE
你好，地址选择器怎样获取区号呢？

### ISSUE THREAD

**Issue by fangood** [gzu-liyujiang/AndroidPicker#18]
我想在选择地址的时候返回区号，不知怎样处理比较好些

**Comment by liyujiang-gzu** [comment]
可以试试修改下面两处，得到地址后，根据地址（areaName）从ArrayList<AddressPicker.Province>中获得区号（areaId）：
```
        ArrayList<AddressPicker.Province> data = new ArrayList<AddressPicker.Province>();
        try {
            String json = AssetsUtils.readText(activity, "city.json");
            data.addAll(JSON.parseArray(json, AddressPicker.Province.class));
        } catch (Exception e) {
            e.printStackTrace();
        }
```
```
 @Override
                public void onAddressPicked(String province, String city, String county) {
                    if (county==null){
                        Toast.makeText(activity, province + city, Toast.LENGTH_LONG).show();
                    } else {
                        Toast.makeText(activity, province + city + county, Toast.LENGTH_LONG).show();
                    }
                }
```

**Comment by fangood** [comment]
感谢您的回复。我是这样修改的。

package com.hiayi.dialog.wheelpicker.picker;

import android.app.Activity;
import android.support.annotation.NonNull;
import android.view.Gravity;
import android.view.View;
import android.widget.LinearLayout;
import com.hiayi.dialog.wheelpicker.widget.WheelView;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;


/**
 * 地址选择器（包括省级、地级、县级）。
 * 地址数据见示例项目的“city.json”，来源于国家统计局官网（http://www.stats.gov.cn/tjsj/tjbz/xzqhdm）
 */
public class AddressPicker extends LinkagePicker {
private OnAddressPickListener onAddressPickListener;
    private boolean hideProvince = false;
    private boolean hideCounty = false;
/**
     * 获取城市编码
     */
private boolean hasCityCode = false;
/**
     * 城市编码
     */
private String cityCode;
/**
     * 城市编码数据
     */
private HashMap<Integer, List<City>> cityMap = new HashMap<Integer, List<City>>();

    public AddressPicker(Activity activity, ArrayList<Province> data, boolean obtainCityCode) {
super(activity);
        this.hasCityCode = obtainCityCode;
parseData(data);
}

/**
     * Instantiates a new Address picker.
     *
     * @param activity the activity
     * @param data     the data
     */
public AddressPicker(Activity activity, ArrayList<Province> data) {
super(activity);
parseData(data);
}

private void parseData(ArrayList<Province> data) {
int provinceSize = data.size();
//添加省
for (int x = 0; x < provinceSize; x++) {
            Province pro = data.get(x);
firstList.add(pro.getAreaName());
ArrayList<City> cities = pro.getCities();
ArrayList<String> xCities = new ArrayList<String>();
            if (hasCityCode) {
cityMap.put(x, cities);
}
            ArrayList<ArrayList<String>> xCounties = new ArrayList<ArrayList<String>>();
            int citySize = cities.size();
//添加地市
for (int y = 0; y < citySize; y++) {
                City cit = cities.get(y);
xCities.add(cit.getAreaName());
ArrayList<County> counties = cit.getCounties();
ArrayList<String> yCounties = new ArrayList<String>();
                int countySize = counties.size();
//添加区县
if (countySize == 0) {
                    yCounties.add(cit.getAreaName());
} else {
for (int z = 0; z < countySize; z++) {
                        yCounties.add(counties.get(z).getAreaName());
}
                }
                xCounties.add(yCounties);
}
secondList.add(xCities);
thirdList.add(xCounties);
}
    }

/**
     * Sets selected item.
     *
     * @param province the province
     * @param city     the city
     * @param county   the county
     */
public void setSelectedItem(String province, String city, String county) {
super.setSelectedItem(province, city, county);
}

/**
     * 隐藏省级行政区，只显示地市级和区县级。
     * 设置为true的话，地址数据中只需要某个省份的即可
     * 参见示例中的“city2.json”
     *
     * @param hideProvince the hide province
     */
public void setHideProvince(boolean hideProvince) {
this.hideProvince = hideProvince;
}

/**
     * 隐藏县级行政区，只显示省级和市级。
     * 设置为true的话，hideProvince将强制为false
     * 数据源依然使用“city.json” 仅在逻辑上隐藏县级选择框。
     *
     * @param hideCounty the hide county
     */
public void setHideCounty(boolean hideCounty) {
this.hideCounty = hideCounty;
}

/**
     * Sets on address pick listener.
     *
     * @param listener the listener
     */
public void setOnAddressPickListener(OnAddressPickListener listener) {
this.onAddressPickListener = listener;
}

@Deprecated
    @Override
public void setOnLinkageListener(OnLinkageListener onLinkageListener) {
throw new UnsupportedOperationException("Please use setOnAddressPickListener instead.");
}

@Override
    @NonNull
protected View makeCenterView() {
if (hideCounty) {
hideProvince = false;
}
if (firstList.size() == 0) {
throw new IllegalArgumentException("please initial data at first, can't be empty");
}
        LinearLayout layout = new LinearLayout(activity);
layout.setOrientation(LinearLayout.HORIZONTAL);
layout.setGravity(Gravity.CENTER);
        final WheelView provinceView = new WheelView(activity);
        final int width = screenWidthPixels / 3;
provinceView.setLayoutParams(new LinearLayout.LayoutParams(width, WRAP_CONTENT));
provinceView.setTextSize(textSize);
provinceView.setTextColor(textColorNormal, textColorFocus);
provinceView.setLineVisible(lineVisible);
provinceView.setLineColor(lineColor);
provinceView.setOffset(offset);
layout.addView(provinceView);
        if (hideProvince) {
            provinceView.setVisibility(View.GONE);
}
final WheelView cityView = new WheelView(activity);
cityView.setLayoutParams(new LinearLayout.LayoutParams(width, WRAP_CONTENT));
cityView.setTextSize(textSize);
cityView.setTextColor(textColorNormal, textColorFocus);
cityView.setLineVisible(lineVisible);
cityView.setLineColor(lineColor);
cityView.setOffset(offset);
layout.addView(cityView);
        final WheelView countyView = new WheelView(activity);
countyView.setLayoutParams(new LinearLayout.LayoutParams(width, WRAP_CONTENT));
countyView.setTextSize(textSize);
countyView.setTextColor(textColorNormal, textColorFocus);
countyView.setLineVisible(lineVisible);
countyView.setLineColor(lineColor);
countyView.setOffset(offset);
layout.addView(countyView);
        if (hideCounty) {
            countyView.setVisibility(View.GONE);
}
        provinceView.setItems(firstList, selectedFirstIndex);
provinceView.setOnWheelViewListener(new WheelView.OnWheelViewListener() {
@Override
public void onSelected(boolean isUserScroll, int selectedIndex, String item) {
selectedFirstText = item;
selectedFirstIndex = selectedIndex;
selectedThirdIndex = 0;
//根据省份获取地市
cityView.setItems(secondList.get(selectedFirstIndex), isUserScroll ? 0 : selectedSecondIndex);
//根据地市获取区县
countyView.setItems(thirdList.get(selectedFirstIndex).get(0), isUserScroll ? 0 : selectedThirdIndex);
}
        });
cityView.setItems(secondList.get(selectedFirstIndex), selectedSecondIndex);
cityView.setOnWheelViewListener(new WheelView.OnWheelViewListener() {
@Override
public void onSelected(boolean isUserScroll, int selectedIndex, String item) {
selectedSecondText = item;
selectedSecondIndex = selectedIndex;
                if (hasCityCode) {
cityCode = cityMap.get(selectedFirstIndex).get(selectedSecondIndex).areaId;
}
//根据地市获取区县
countyView.setItems(thirdList.get(selectedFirstIndex).get(selectedSecondIndex), isUserScroll ? 0 : selectedThirdIndex);
}
        });
countyView.setItems(thirdList.get(selectedFirstIndex).get(selectedSecondIndex), selectedThirdIndex);
countyView.setOnWheelViewListener(new WheelView.OnWheelViewListener() {
@Override
public void onSelected(boolean isUserScroll, int selectedIndex, String item) {
selectedThirdText = item;
selectedThirdIndex = selectedIndex;
}
        });
        return layout;
}

@Override
public void onSubmit() {
if (onAddressPickListener != null) {
if (hideCounty) {
if (hasCityCode) {
                    clearCityData();
onAddressPickListener.onAddressPicked(selectedFirstText, selectedSecondText, null, cityCode);
} else {
onAddressPickListener.onAddressPicked(selectedFirstText, selectedSecondText, null);
}
            } else {
if (hasCityCode) {
                    clearCityData();
onAddressPickListener.onAddressPicked(selectedFirstText, selectedSecondText, selectedThirdText, cityCode);
} else {
onAddressPickListener.onAddressPicked(selectedFirstText, selectedSecondText, selectedThirdText);
}
            }
        }
    }

/**
     * 清理数据
     */
private void clearCityData() {
if (cityMap != null) {
cityMap.clear();
}
    }

/**
     * The interface On address pick listener.
     */
public interface OnAddressPickListener {

/**
         * On address picked.
         *
         * @param province the province
         * @param city     the city
         * @param county   the county ，if {@hideCounty} is true，this is null
         */
void onAddressPicked(String province, String city, String county);

        void onAddressPicked(String province, String city, String county, String cityCode);

}

/**
     * The type Area.
     */
public abstract static class Area {
/**
         * The Area id.
         */
String areaId;
/**
         * The Area name.
         */
String areaName;

/**
         * Gets area id.
         *
         * @return the area id
         */
public String getAreaId() {
return areaId;
}

/**
         * Sets area id.
         *
         * @param areaId the area id
         */
public void setAreaId(String areaId) {
this.areaId = areaId;
}

/**
         * Gets area name.
         *
         * @return the area name
         */
public String getAreaName() {
return areaName;
}

/**
         * Sets area name.
         *
         * @param areaName the area name
         */
public void setAreaName(String areaName) {
this.areaName = areaName;
}

@Override
public String toString() {
return "areaId=" + areaId + ",areaName=" + areaName;
}

    }

/**
     * The type Province.
     */
public static class Province extends Area {
/**
         * The Cities.
         */
ArrayList<City> cities = new ArrayList<City>();

/**
         * Gets cities.
         *
         * @return the cities
         */
public ArrayList<City> getCities() {
return cities;
}

/**
         * Sets cities.
         *
         * @param cities the cities
         */
public void setCities(ArrayList<City> cities) {
this.cities = cities;
}

    }

/**
     * The type City.
     */
public static class City extends Area {
private ArrayList<County> counties = new ArrayList<County>();

/**
         * Gets counties.
         *
         * @return the counties
         */
public ArrayList<County> getCounties() {
return counties;
}

/**
         * Sets counties.
         *
         * @param counties the counties
         */
public void setCounties(ArrayList<County> counties) {
this.counties = counties;
}

    }

/**
     * The type County.
     */
public static class County extends Area {
    }

}








在 2016-05-24 06:52:05，"穿青人" <notifications@github.com> 写道：


可以试试修改下面两处，得到地址后，根据地址（areaName）从ArrayList中获得区号（areaId）：

        ArrayList<AddressPicker.Province> data = new ArrayList<AddressPicker.Province>();
        try {
            String json = AssetsUtils.readText(activity, "city.json");
            data.addAll(JSON.parseArray(json, AddressPicker.Province.class));
        } catch (Exception e) {
            e.printStackTrace();
        }

 @Override
                public void onAddressPicked(String province, String city, String county) {
                    if (county==null){
                        Toast.makeText(activity, province + city, Toast.LENGTH_LONG).show();
                    } else {
                        Toast.makeText(activity, province + city + county, Toast.LENGTH_LONG).show();
                    }
                }

**Comment by liyujiang-gzu** [comment]
最新版已经支持获取区号
