### ISSUE TITLE
由混淆导致的crash

### ISSUE THREAD

**Issue by blueskyfred1** [gzu-liyujiang/AndroidPicker#21]
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to cn.qqtheme.framework.picker.AddressPicker$City
  
已经加了
-keep class cn.qqtheme.framework.entity.** { *;}
-keep class cn.qqtheme.framework.picker.AddressPicker$* { *;}

**Comment by blueskyfred1** [comment]
补充
  java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to cn.qqtheme.framework.picker.AddressPicker$City

**Comment by blueskyfred1** [comment]
已经解决了，是fastjson混淆的问题，加上 -keepattributes Signature 就解决了，JSON.parseArray(json, AddressPicker.Province.class)这里会用到json解析，如果用到fastjson，是不是项目配置中必须加个 -keepattributes Signature ？

**Comment by liyujiang-gzu** [comment]
@blueskyfred1 估计是的吧。一般引用了json类的包或者orm类的包要特别注意混淆问题，不能混淆实体类、泛型和注解，下面这个是表示不混淆泛型和注解：
```
-keepattributes Signature  
-keepattributes *Annotation*
```
