### ISSUE TITLE
条件选择中 布局宽度不能占满屏幕

### ISSUE THREAD

**Issue by Wudelin** [gzu-liyujiang/AndroidPicker#211]

**Comment by CleverMod** [comment]
WindowManager.LayoutParams params = picker.getWindow().getAttributes();
params.width = 屏幕宽度;

**Comment by 1458883958** [comment]
能不能使用自己的地址JSON来实现地址选择（是否必须要以demo中省市格式来）；以及时间选择器好像不能只有日（看的源码）

**Comment by liyujiang-gzu** [comment]
> WindowManager.LayoutParams params = picker.getWindow().getAttributes();
> params.width = 屏幕宽度;

屏幕宽度使用`MATCH_PARENT`或者`getResources().getDisplayMetrics().widthPixels`可能存在兼容性问题：
```java
WindowManager wm = (WindowManager) appContext.getSystemService(Context.WINDOW_SERVICE);
Point point = new Point();
wm.getDefaultDisplay().getSize(point);
picker.setWidth(point.x);
picker.show();
```
