### ISSUE TITLE
SinglePicker 添加数据后 数据重复 重复无数次 就像死循环一直添加数据

### ISSUE THREAD

**Issue by xuewei666** [gzu-liyujiang/AndroidPicker#215]
public void onSinglePicker(List<QueryOrgBean.DataBean> datalist) {
        List<GoodsCategory> data0 = new ArrayList<>();
        for (int i = 0; i < datalist.size(); i++) {
            int orgid = datalist.get(i).getOrgid();
            String orgname = datalist.get(i).getOrgname();
            data0.add(new GoodsCategory(orgid, orgname));
        }

        SinglePicker<GoodsCategory> picker = new SinglePicker<>(this, data0);
        picker.setCanceledOnTouchOutside(false);
        picker.setSelectedIndex(1);
        picker.setCycleDisable(false);
        picker.setOnItemPickListener(new SinglePicker.OnItemPickListener<GoodsCategory>() {
            @Override
            public void onItemPicked(int index, GoodsCategory item) {
               // showToast("index=" + index + ", id=" + item.getId() + ", name=" + item.getName());
            }
        });
        picker.show();
    }

**Comment by xuewei666** [comment]
就是 只添加一条数据 这调数据也会重复出现无数个

**Comment by liyujiang-gzu** [comment]
禁用循环：picker.setCycleDisable(true);
