### ISSUE TITLE
地址数据来源是哪的？

### ISSUE THREAD

**Issue by ysmintor** [gzu-liyujiang/AndroidPicker#23]
楼主的数据比较新，但没有对应的街道数据，不知道能否提供来源，我想引入街道，在选择省市区后再确定街道，街道数据由省市区确定后向服务器查询。不知道能否提供@gzu-liyujiang

**Comment by liyujiang-gzu** [comment]
@ysmintor 来源于国家统计局官网：http://www.stats.gov.cn/tjsj/tjbz/xzqhdm

**Comment by ysmintor** [comment]
@liyujiang-gzu 不会吧？我们开发也是查看过，不过上面是14年的数据。不是你这里面最新的数据，比如说深圳市吧
国家统计局的数据是
···xml
440301  　　　市辖区

440303  　　　罗湖区

440304  　　　福田区

440305  　　　南山区

440306  　　　宝安区

440307  　　　龙岗区

440308  　　　盐田区

```
显然你这个Json里的数据是有最新的光明新区、成华新区等等，所以我相信楼主的json是从别的地方来的吧?

**Comment by ysmintor** [comment]
# @liyujiang-gzu 是自己做的Json数据吗？如果是其它 地方找的，能否告知？

**Comment by liyujiang-gzu** [comment]
@ysmintor 一两年了，时间太久，我忘记是从哪里搞来整理的了，我看以前代码里注释的数据来源地址是国家统计局
