### ISSUE TITLE
SinglePicker  使用对象 会出现java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by xusigh** [gzu-liyujiang/AndroidPicker#236]
SinglePicker  使用对象 会出现java.lang.IllegalArgumentException: please implements cn.qqtheme.framework.entity.WheelItem

**Comment by l376571926** [comment]
> SinglePicker 使用对象 会出现java.lang.IllegalArgumentException: please implements cn.qqtheme.framework.entity.WheelItem

在显示之前调用：
picker.setItemWidthInDp(120);

**Comment by liyujiang-gzu** [comment]
你的对象需实现WheelItem提供一个字符串做显示的名称
