### ISSUE TITLE
日期选择器setRang(Today,)，选择今天之后的日期，应该是选择今天之前的日期

### ISSUE THREAD

**Issue by jack22001** [gzu-liyujiang/AndroidPicker#244]
![image](https://user-images.githubusercontent.com/16815447/124116739-dc90d080-daa1-11eb-9f7b-cdb33663d5df.png)
比如选择生日，应该选择当天之前日期而不是之后，用了picker.wheelLayout.setRange(today, DateEntity.target(1900, 1, 1), today)这个方法之后，今年之前的日期选不了，楼主麻烦看下

**Comment by liyujiang-gzu** [comment]
> ![image](https://user-images.githubusercontent.com/16815447/124116739-dc90d080-daa1-11eb-9f7b-cdb33663d5df.png)
> 比如选择生日，应该选择当天之前日期而不是之后，用了picker.wheelLayout.setRange(today, DateEntity.target(1900, 1, 1), today)这个方法之后，今年之前的日期选不了，楼主麻烦看下

选择今天之前的日期请用`setRange(DateEntity.target(1900, 1, 1), today,today)`，最小的日期放在第一个参数，可参阅本库自带的 `BirthdayPicker`的实现方式。

**Comment by liyujiang-gzu** [comment]
> 用了picker.wheelLayout.setRange(today, DateEntity.target(1900, 1, 1), today)这个方法之后，今年之前的日期选不了，楼主麻烦看下


是因为这里代码还不严谨，应该确保startValue<endValue：
![image](https://user-images.githubusercontent.com/16816717/124214156-608b9c80-db24-11eb-8564-b085b5eb5617.png)

**Comment by liyujiang-gzu** [comment]
See version [3.0.5](https://jitpack.io/#gzu-liyujiang/AndroidPicker/3.0.5)
