### ISSUE TITLE
TimePicker java设置显示秒HOUR_24_HAS_SECOND无效，

### ISSUE THREAD

**Issue by huyi3211** [gzu-liyujiang/AndroidPicker#249]
![image](https://user-images.githubusercontent.com/20216844/125617917-7ffa6bdd-4102-450f-9c9f-1050f6a0ed73.png) 总是比java设置显示模式后执行

**Comment by liyujiang-gzu** [comment]
[3.0.7](https://jitpack.io/#gzu-liyujiang/AndroidPicker/3.0.7) 版本开始已修复
