### ISSUE TITLE
项目作为aar打包时一直提示DateTimeView找不到

### ISSUE THREAD

**Issue by Seawn** [gzu-liyujiang/AndroidPicker#250]
/databinding/NotificationTemplatePartTimeBinding.java:7: 错误: 找不到符号
import android.widget.DateTimeView;
                     ^
  符号:   类 DateTimeView
  位置: 程序包 android.widget

**Comment by liyujiang-gzu** [comment]
你导错包了吧？DatePicker导入成android自带的了，本项目并没用到`android.widget.DateTimeView`

**Comment by Seawn** [comment]
好的我检查一下
