### ISSUE TITLE
有个滑动的bug

### ISSUE THREAD

**Issue by ljphawk** [gzu-liyujiang/AndroidPicker#251]
举例子：时间选择器，滑动“年”的时候，在"年"未停止的情况下，快速去滑动“月或日”，有概率会导致 “年”这个选项变成空白

**Comment by liyujiang-gzu** [comment]
> 举例子：时间选择器，滑动“年”的时候，在"年"未停止的情况下，快速去滑动“月或日”，有概率会导致 “年”这个选项变成空白

快速滑动的处时候理是有点问题，上一个滚动还没结束导致混乱

**Comment by liyujiang-gzu** [comment]
[新版本 3.0.8](https://jitpack.io/#gzu-liyujiang/AndroidPicker/3.0.8) 已优化

**Comment by ljphawk** [comment]
> [新版本 3.0.8](https://jitpack.io/#gzu-liyujiang/AndroidPicker/3.0.8) 已优化

感谢

**Comment by liyujiang-gzu** [comment]
> > [新版本 3.0.8](https://jitpack.io/#gzu-liyujiang/AndroidPicker/3.0.8) 已优化
> 
> 感谢

从3.0.8开始对滚动、联动都有所优化，可以帮忙验证一下
