### ISSUE TITLE
12小时制没有AM和PM

### ISSUE THREAD

**Issue by CGmaybe10** [gzu-liyujiang/AndroidPicker#252]
12小时制没有AM和PM

**Comment by liyujiang-gzu** [comment]
嗯，12小时制的数据显示还有bug

**Comment by liyujiang-gzu** [comment]
![image](https://user-images.githubusercontent.com/16816717/126451584-3c3da334-d5b2-4e44-89d8-3b259013e154.png)

新版本修复

**Comment by liyujiang-gzu** [comment]
[新版本 3.0.8](https://jitpack.io/#gzu-liyujiang/AndroidPicker/3.0.8) 已优化

**Comment by CGmaybe10** [comment]
AM和PM应该也是一个wheel view，1-12，是指白点或者晚上

**Comment by liyujiang-gzu** [comment]
> AM和PM应该也是一个wheel view，1-12，是指白点或者晚上

额，这样组合是要合理一点

**Comment by liyujiang-gzu** [comment]
> AM和PM应该也是一个wheel view，1-12，是指白点或者晚上

3.1.0 版本重新调整了，稍候发布：
![image](https://user-images.githubusercontent.com/16816717/127627144-c23e317d-6a55-4b5b-9d80-ec30388d4e6c.png)
