### ISSUE TITLE
如何更改24小时的UI 跟数据

### ISSUE THREAD

**Issue by pzb1834** [gzu-liyujiang/AndroidPicker#253]

**Comment by liyujiang-gzu** [comment]
更改UI：`picker.getXXX().setXXX`；
更改数据：`picker.getWheelLayout().setRange()`；

**Comment by pzb001025** [comment]
rootLayout.setBackgroundColor(0xFFFFFFFF);更改这个是需要获取那个View

**Comment by pzb001025** [comment]
已解决

**Comment by liyujiang-gzu** [comment]
> rootLayout.setBackgroundColor(0xFFFFFFFF);更改这个是需要获取那个View

这个`rootLayout`可以通过`picker.getContentView()`获取

**Comment by pzb001025** [comment]
rootLayout这个view没有get方法

**Comment by liyujiang-gzu** [comment]
> rootLayout

rootLayout是赋值给contentVIew的
![image](https://user-images.githubusercontent.com/16816717/126956821-d869dc4c-6ee8-44c9-af2b-05664ea7cc72.png)
![image](https://user-images.githubusercontent.com/16816717/126956884-15820e20-3c31-423c-9352-894cfa35eb57.png)

**Comment by pzb1834** [comment]
嗯嗯
