### ISSUE TITLE
HOUR_24_NO_SECOND 24小时制 只有11点--23点?

### ISSUE THREAD

**Issue by pzb001025** [gzu-liyujiang/AndroidPicker#254]

**Comment by liyujiang-gzu** [comment]
默认时间范围是当前时间到23点，需要自定义，用`picker.getWheelLayout().setRange()`

**Comment by pzb001025** [comment]
我使用setpadding设置内边距 没有生效..

**Comment by liyujiang-gzu** [comment]
> 我使用setpadding设置内边距 没有生效..

试试获取对应的视图来设置：picker.getContentView().setPadding()、picker.getBodyView().setPadding()

**Comment by pzb1834** [comment]
这些都有没有生效

**Comment by liyujiang-gzu** [comment]
> 这些都有没有生效

不会吧，这不是有效的吗：
```java
        int padding = (int) (view.getResources().getDisplayMetrics().density * 20);
        picker.getContentView().setPadding(padding, padding, padding, padding);
        picker.getWheelLayout().setPadding(padding, padding, padding, padding);
```
![image](https://user-images.githubusercontent.com/16816717/127106123-12fabb36-d1f5-4e7a-8e4f-f66df0a43436.png)

**Comment by pzb001025** [comment]
可能是我顺序错了吧，我在看看..谢谢大佬
