### ISSUE TITLE
AddressPicker地址选择器, 能用什么方法在添加进去个不限

### ISSUE THREAD

**Issue by harryhasai** [gzu-liyujiang/AndroidPicker#258]
如题, 业务需求需要有筛选功能, 目前的地址选择器里面只要选择了某个省市区就不可逆了, 能否添加个不限进去, 或者告诉我有啥方法可以自己手动添加数据进去

当前使用版本
implementation 'com.github.gzu-liyujiang.AndroidPicker:AddressPicker:3.1.0'

**Comment by harryhasai** [comment]
找到了个方法曲线救国了一下
mAddressPicker.setOnAddressLoadListener(new OnAddressLoadListener() {
                    @Override
                    public void onAddressLoadStarted() {

                    }

                    @Override
                    public void onAddressLoadFinished(@NonNull List<ProvinceEntity> data) {//手动添加不限的数据
                        if (mAddressPickerData == null) {
                            mAddressPickerData = data;
                            ProvinceEntity entity = new ProvinceEntity();
                            entity.setName("不限");
                            entity.setCode("");
                            mAddressPickerData.add(0, entity);
                            mAddressPicker.onAddressReceived(mAddressPickerData);
                        }
                    }
                });
在监听里自己拿到数据重新set

**Comment by harryhasai** [comment]
希望大佬留一个自己手动添加数据的口, 感谢大佬!

**Comment by liyujiang-gzu** [comment]
> 如题, 业务需求需要有筛选功能, 目前的地址选择器里面只要选择了某个省市区就不可逆了, 能否添加个不限进去, 或者告诉我有啥方法可以自己手动添加数据进去
> 
> 当前使用版本
> implementation 'com.github.gzu-liyujiang.AndroidPicker:AddressPicker:3.1.0'

可以试试在你的app模块的assets目录下的放置`china_address.json`覆盖AddressPicker自带的：
```
[
  {
    "code": "0",
    "name": "不限",
    "cityList": [
      {
        "code": "0",
        "name": "不限",
        "areaList": [
          {
            "code": "0",
            "name": "不限"
          }
      }
   }，
  {
    "code": "110000",
    "name": "北京市",
    "cityList": [
      {
        "code": "110000",
        "name": "北京市",
        "areaList": [
          {
            "code": "110101",
            "name": "东城区"
          },
          {
            "code": "110102",
            "name": "西城区"
          },
          {
            "code": "110105",
...
```

**Comment by harryhasai** [comment]
按照大佬的方式果然解决了, 谢谢大佬
