### ISSUE TITLE
setRange 不生效哦

### ISSUE THREAD

**Issue by 1656150492** [gzu-liyujiang/AndroidPicker#259]
BirthdayPicker birthdayPicker = new BirthdayPicker(MainActivity.this);
        birthdayPicker.setBackground(getResources().getDrawable(R.drawable.bg_top_radius_8));
        birthdayPicker.getOkView().setTextSize(14);
        birthdayPicker.getCancelView().setTextSize(14);
        birthdayPicker.setBodyHeight(200);
        DateWheelLayout wheelLayout = birthdayPicker.getWheelLayout();
        wheelLayout.setCurvedEnabled(true);
        wheelLayout.setVisibleItemCount(9);
        wheelLayout.setCurtainEnabled(true);
        wheelLayout.setCurtainColor(getResources().getColor(R.color.bgIndicator));
        wheelLayout.setCyclicEnabled(true);                         //循环显示
        wheelLayout.setTextColor(getResources().getColor(R.color.fontDatePickerNormalColor));
        wheelLayout.setSelectedTextColor(getResources().getColor(R.color.fontDatePickerSelectedColor));
        wheelLayout.getYearWheelView().setRange(1970, Calendar.getInstance().get(Calendar.YEAR), 1);
        birthdayPicker.show();

不生效哦

**Comment by liyujiang-gzu** [comment]
> ```
>     BirthdayPicker birthdayPicker = new BirthdayPicker(MainActivity.this);
>     birthdayPicker.setBackground(getResources().getDrawable(R.drawable.bg_top_radius_8));
>     birthdayPicker.getOkView().setTextSize(14);
>     birthdayPicker.getCancelView().setTextSize(14);
>     birthdayPicker.setBodyHeight(200);
>     DateWheelLayout wheelLayout = birthdayPicker.getWheelLayout();
>     wheelLayout.setCurvedEnabled(true);
>     wheelLayout.setVisibleItemCount(9);
>     wheelLayout.setCurtainEnabled(true);
>     wheelLayout.setCurtainColor(getResources().getColor(R.color.bgIndicator));
>     wheelLayout.setCyclicEnabled(true);                         //循环显示
>     wheelLayout.setTextColor(getResources().getColor(R.color.fontDatePickerNormalColor));
>     wheelLayout.setSelectedTextColor(getResources().getColor(R.color.fontDatePickerSelectedColor));
>     wheelLayout.getYearWheelView().setRange(1970, Calendar.getInstance().get(Calendar.YEAR), 1);
>     birthdayPicker.show();
> ```
> 
> 不生效哦

`BirthdayPicker#initData`里限定死了，范围为100年，在外部设置后也会被initData里的覆盖。这个范围不适用于你的话，可以使用`DatePicker`来设置。

**Comment by 1656150492** [comment]
@liyujiang-gzu  DatePicker有办法把年月日设置在NumberPicker里边吗
