### ISSUE TITLE
地址选择崩溃

### ISSUE THREAD

**Issue by NuonuoLabs** [gzu-liyujiang/AndroidPicker#261]
选择湖北省 天门市  由于后面没有区 点击会崩溃

**Comment by xiangyuecn** [comment]
可以参考 #332 更新获取到最新版的省市区数据，对于这些 省直辖县级市、直筒子市 都进行了很好的处理，全部数据都是3级结构，比如：湖北-天门，是没有区级的，会填充一个同名的区级，变成：湖北-天门-天门

建议开发当天转换得到新文件，这样就能使用到最新版本数据，所使用的数据源是我的开源库 https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov ，基本上月更，除了省市区乡镇四级区划外，还有坐标边界数据。欢迎用 #332 的代码在线转成china_address.json
