### ISSUE TITLE
用于自定义滚轮选择器 WheelView 能否支持选中的字体变为粗体呢？

### ISSUE THREAD

**Issue by PeOS-China** [gzu-liyujiang/AndroidPicker#267]
你好，我在commi日志看到4.1.0支持滚轮选择器选中项文字支持加大加粗；但WheelView组件升级到最新4.1.0版本后，仍找不到wheel_itemTextBoldSelected属性

**Comment by liyujiang-gzu** [comment]
> 你好，我在commi日志看到4.1.0支持滚轮选择器选中项文字支持加大加粗；但WheelView组件升级到最新4.1.0版本后，仍找不到wheel_itemTextBoldSelected属性

我检查了，是加的有`wheel_itemTextBoldSelected`的，gradle sync 试试。
![image](https://user-images.githubusercontent.com/16816717/140014345-3c282485-0f1c-4b41-9d18-c48a6ee75ebd.png)

**Comment by liyujiang-gzu** [comment]
`4.1.1`版本开始支持，不是`4.1.0`
