### ISSUE TITLE
4.1.2版本的wheel_itemTextSizeSelected和wheel_itemTextBoldSelected 无效

### ISSUE THREAD

**Issue by PeOS-China** [gzu-liyujiang/AndroidPicker#268]
下面代码是WheelView的布局文件和设置文件，wheel_itemTextSizeSelected和wheel_itemTextBoldSelected无法在界面上反应出来。并且在setDefaultPosition的，会有滚动的动画出现，在4.1.0不会有这种情况。
<img width="452" alt="image" src="https://user-images.githubusercontent.com/8873336/140035177-875697b0-caf1-495a-b866-fc94a01ff011.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/8873336/140035298-717d5f9e-504b-48da-b670-da898cfda168.png">

上面代码运行的效果：

<img width="481" alt="image" src="https://user-images.githubusercontent.com/8873336/140034983-9f97a10f-6b92-442d-9143-26c878893872.png">

**Comment by liyujiang-gzu** [comment]
不知道是不是用法、场景问题，你运行下这个项目的demo看看有效果没？

**Comment by PeOS-China** [comment]
总算找到原因，在WheelView drawItemRect，如果selectedTextColor是 -1 会被认为是没有设置颜色，而实际上，-1 是白色！！！建议使用Integer.MAX_VALUE来表示没有设置颜色
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/8873336/143425140-6531f8c8-b682-496f-ba62-f5d7297427bd.png">

**Comment by PeOS-China** [comment]
@liyujiang-gzu 还有一个需要完善的，但正常字体和选中字体一样的时候，wheel_itemTextBoldSelected 的逻辑没有包含在里面，导致失效
<img width="833" alt="image" src="https://user-images.githubusercontent.com/8873336/143427930-b29874e3-7c66-4f16-948a-3674a1bf4892.png">

**Comment by liyujiang-gzu** [comment]
> @liyujiang-gzu 总算找到原因，在WheelView drawItemRect，如果selectedTextColor是 -1 会被认为是没有设置颜色，而实际上，-1 是白色！！！建议使用Integer.MAX_VALUE来表示没有设置颜色 <img alt="image" width="1359" src="https://user-images.githubusercontent.com/8873336/143425140-6531f8c8-b682-496f-ba62-f5d7297427bd.png">

嗯，颜色的判断失误问题，也引起了[这个bug](https://github.com/gzu-liyujiang/AndroidPicker/issues/274)

**Comment by liyujiang-gzu** [comment]
> @liyujiang-gzu 总算找到原因，在WheelView drawItemRect，如果selectedTextColor是 -1 会被认为是没有设置颜色，而实际上，-1 是白色！！！建议使用Integer.MAX_VALUE来表示没有设置颜色 <img alt="image" width="1359" src="https://user-images.githubusercontent.com/8873336/143425140-6531f8c8-b682-496f-ba62-f5d7297427bd.png">

除了使用Integer.MAX_VALUE，也可以将int改为Integer，使用null来判断。
