### ISSUE TITLE
选择年之后，怎么禁止月日重置到1

### ISSUE THREAD

**Issue by uHone** [gzu-liyujiang/AndroidPicker#269]
看了下demo都是重置，这个能关闭吗，感谢

**Comment by liyujiang-gzu** [comment]
> 看了下demo都是重置，这个能关闭吗，感谢

暂时还不支持这个设置，后续版本再加个开关

**Comment by liyujiang-gzu** [comment]
@uHone  已经支持，试试这个临时版本：
```groovy
implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:374894c193'
```
```java
picker.getWheelLayout().setResetWhenLinkage(false);
```

**Comment by liyujiang-gzu** [comment]
https://user-images.githubusercontent.com/16816717/140618396-1d84b096-d326-4d5b-a882-8da00ec596e3.mp4

**Comment by liyujiang-gzu** [comment]
参阅 [4.1.4及其之后的版本](https://github.com/gzu-liyujiang/AndroidPicker/releases/tag/4.1.5) 版本
