### ISSUE TITLE
时间间隔现在支持了吗？ 

### ISSUE THREAD

**Issue by nxnyk** [gzu-liyujiang/AndroidPicker#270]
10分钟一个间隔

**Comment by liyujiang-gzu** [comment]
> 10分钟一个间隔

间隔目前时间选择器还不支持，只有数字选择器支持

**Comment by nxnyk** [comment]
> > 10分钟一个间隔
> 
> 间隔目前时间选择器还不支持，只有数字选择器支持

好吧，目前只能这样实现嘛

**Comment by liyujiang-gzu** [comment]
> > > 10分钟一个间隔
> > 
> > 
> > 间隔目前时间选择器还不支持，只有数字选择器支持
> 
> 好吧，目前只能这样实现嘛

增加这个时间间隔设置项应该是容易的，稍候我看一下。

**Comment by liyujiang-gzu** [comment]
@nxnyk 试试这个临时版本：` implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:5dc0fa945f`

**Comment by liyujiang-gzu** [comment]
[4.1.4 版本](https://github.com/gzu-liyujiang/AndroidPicker/blob/master/ChangeLog.md#414---20211116)开始已支持

**Comment by nxnyk** [comment]
> [4.1.4 版本](https://github.com/gzu-liyujiang/AndroidPicker/blob/master/ChangeLog.md#414---20211116)开始已支持

卧槽，老哥牛！！！感谢老哥！
