### ISSUE TITLE
关于日期时间选择器-可以实现即选择单个日期又可以选择区域内日期么？

### ISSUE THREAD

**Issue by TeaHerbal** [gzu-liyujiang/AndroidPicker#271]

**Comment by liyujiang-gzu** [comment]
选择区域内日期指的是类似于日历日期选择器的选择一个日期范围吗？

**Comment by TeaHerbal** [comment]
感谢您的回复，是日历选择器，需求是：可以选择一段时间也可以选择单个日期的日历，我目前的实现方式修改了您的ClalendarAdapter中的onCalendarDayClick方法代码； @Override
    public void onCalendarDayClick(Date date) {
        if (null == date) {
            return;
        }
        if (null == lastClickDate || singleMode) {
            lastClickDate = date;
            select(date, date).refresh();
            if (null != onDateSelectedListener) {
                onDateSelectedListener.onSingleSelected(date);
            }
            if(!singleMode&&null != onDateSelectedListener){
                onDateSelectedListener.onRangeSelected(date, date);
            }
            return;
        }
        if (lastClickDate.getTime() >= date.getTime()) {
            lastClickDate = date;
            select(date, date).refresh();
            if (null != onDateSelectedListener) {
                onDateSelectedListener.onSingleSelected(date);
            }
            if(!singleMode&&lastClickDate.getTime()==date.getTime()){
                select(date, date).refresh();
                onDateSelectedListener.onRangeSelected(date, date);
            }
        } else {
            select(lastClickDate, date).refresh();
            if (null != onDateSelectedListener) {
                onDateSelectedListener.onRangeSelected(lastClickDate, date);
            }
            lastClickDate = null;
        }
    }

**Comment by liyujiang-gzu** [comment]
> 感谢您的回复，是日历选择器，需求是：可以选择一段时间也可以选择单个日期的日历，我目前的实现方式修改了您的ClalendarAdapter中的onCalendarDayClick方法代码； @OverRide public void onCalendarDayClick(Date date) { if (null == date) { return; } if (null == lastClickDate || singleMode) { lastClickDate = date; select(date, date).refresh(); if (null != onDateSelectedListener) { onDateSelectedListener.onSingleSelected(date); } if(!singleMode&&null != onDateSelectedListener){ onDateSelectedListener.onRangeSelected(date, date); } return; } if (lastClickDate.getTime() >= date.getTime()) { lastClickDate = date; select(date, date).refresh(); if (null != onDateSelectedListener) { onDateSelectedListener.onSingleSelected(date); } if(!singleMode&&lastClickDate.getTime()==date.getTime()){ select(date, date).refresh(); onDateSelectedListener.onRangeSelected(date, date); } } else { select(lastClickDate, date).refresh(); if (null != onDateSelectedListener) { onDateSelectedListener.onRangeSelected(lastClickDate, date); } lastClickDate = null; } }

可以修改下增加一个开关，允许同时可以单选+范围选

**Comment by liyujiang-gzu** [comment]
[4.1.5版本](https://github.com/gzu-liyujiang/AndroidPicker/blob/master/ChangeLog.md#415---20211205) 开始支持
