### ISSUE TITLE
三方字体支持

### ISSUE THREAD

**Issue by SmallWinter** [gzu-liyujiang/AndroidPicker#273]
首先支持大佬提供便携使用的view。
项目中使用三方字体，暂时没看到支持的选项，不知道是否考虑加入三方字体的支持？

**Comment by liyujiang-gzu** [comment]
> 首先支持大佬提供便携使用的view。 项目中使用三方字体，暂时没看到支持的选项，不知道是否考虑加入三方字体的支持？

支持设置字体的，调用`picker.getWheelLayout().setTypeface(...)`

**Comment by SmallWinter** [comment]
谢谢佬
