### ISSUE TITLE
DateWheelLayout年月日的lable滑动年Wheel的问题

### ISSUE THREAD

**Issue by ljphawk** [gzu-liyujiang/AndroidPicker#278]
DateWheelLayout年月日模式+lable显示，滑动年Wheel偶尔会导致 月日选中那一行的位置整体上移

        <com.github.gzuliyujiang.wheelpicker.widget.DateWheelLayout
            android:id="@+id/dateWheelLayout"
            android:layout_width="566dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:background="@color/white"
            android:gravity="center_horizontal"
            app:layout_constraintBottom_toTopOf="@id/tv_confirm"
            app:wheel_atmosphericEnabled="true"
            app:wheel_dateMode="year_month_day"
            app:wheel_dayLabel="日"
            app:wheel_indicatorEnabled="false"
            app:wheel_itemSpace="15dp"
            app:wheel_itemTextColor="@color/c_999"
            app:wheel_itemTextColorSelected="@color/colorPrimary"
            app:wheel_itemTextSize="16sp"
            app:wheel_itemTextSizeSelected="28sp"
            app:wheel_monthLabel="月"
            app:wheel_visibleItemCount="7"
            app:wheel_yearLabel="年" />

**Comment by ljphawk** [comment]
<com.github.gzuliyujiang.wheelpicker.widget.DateWheelLayout
            android:id="@+id/dateWheelLayout"
            android:layout_width="566dp"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:background="@color/white"
            android:gravity="center_horizontal"
            app:layout_constraintBottom_toTopOf="@id/tv_confirm"
            app:wheel_atmosphericEnabled="true"
            app:wheel_dateMode="year_month_day"
            app:wheel_dayLabel="日"
            app:wheel_indicatorEnabled="false"
            app:wheel_itemSpace="15dp"
            app:wheel_itemTextColor="@color/c_999"
            app:wheel_itemTextColorSelected="@color/colorPrimary"
            app:wheel_itemTextSize="16sp"
            app:wheel_itemTextSizeSelected="28sp"
            app:wheel_monthLabel="月"
            app:wheel_visibleItemCount="7"
            app:wheel_yearLabel="年" />

**Comment by liyujiang-gzu** [comment]
> DateWheelLayout年月日模式+lable显示，滑动年Wheel偶尔会导致 月日选中那一行的位置整体上移
> 
> ```
>     <com.github.gzuliyujiang.wheelpicker.widget.DateWheelLayout
>         android:id="@+id/dateWheelLayout"
>         android:layout_width="566dp"
>         android:layout_height="wrap_content"
>         android:layout_gravity="center_horizontal"
>         android:background="@color/white"
>         android:gravity="center_horizontal"
>         app:layout_constraintBottom_toTopOf="@id/tv_confirm"
>         app:wheel_atmosphericEnabled="true"
>         app:wheel_dateMode="year_month_day"
>         app:wheel_dayLabel="日"
>         app:wheel_indicatorEnabled="false"
>         app:wheel_itemSpace="15dp"
>         app:wheel_itemTextColor="@color/c_999"
>         app:wheel_itemTextColorSelected="@color/colorPrimary"
>         app:wheel_itemTextSize="16sp"
>         app:wheel_itemTextSizeSelected="28sp"
>         app:wheel_monthLabel="月"
>         app:wheel_visibleItemCount="7"
>         app:wheel_yearLabel="年" />
> ```

您用的是哪个版本？这个问题我有遇到过，**4.1.3及4.1.4版本已做了优化**，暂时还没复现。

**Comment by liyujiang-gzu** [comment]
@ljphawk See version [4.1.6](https://jitpack.io/#gzu-liyujiang/AndroidPicker/4.1.6)

**Comment by liyujiang-gzu** [comment]
duplicate #279
