### ISSUE TITLE
如果设置了itemtextsize，滑动item，其他的item就会错位。

### ISSUE THREAD

**Issue by xiaoyaobai** [gzu-liyujiang/AndroidPicker#279]
![image](https://user-images.githubusercontent.com/13116470/145536513-78fb457d-cb99-4b54-b84e-cc142184f4d6.png)

**Comment by xiaoyaobai** [comment]
![image](https://user-images.githubusercontent.com/13116470/145537316-23491f32-a0d1-4b2a-991c-9297daa6fdab.png)
就像这样。

**Comment by liyujiang-gzu** [comment]
> ![image](https://user-images.githubusercontent.com/13116470/145537316-23491f32-a0d1-4b2a-991c-9297daa6fdab.png) 就像这样。

这个问题是4.1.2版本支持字号加大加粗引起的，4.1.3及4.1.4版本做了优化，4.1.4版本任然还复现这个问题吗？。

**Comment by xiaoyaobai** [comment]
implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:4.1.5'

**Comment by xiaoyaobai** [comment]
> > ![image](https://user-images.githubusercontent.com/13116470/145537316-23491f32-a0d1-4b2a-991c-9297daa6fdab.png) 就像这样。
> 
> 这个问题是4.1.2版本支持字号加大加粗引起的，4.1.3及4.1.4版本做了优化，4.1.4版本任然还复现这个问题吗？。

implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:4.1.5'  我添加的是这个版本。您可以自己尝试一下。

**Comment by liyujiang-gzu** [comment]
@xiaoyaobai 试试这个版本，验证一下看看：`implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:6139b39c44'`

**Comment by liyujiang-gzu** [comment]
```xml
        <com.github.gzuliyujiang.wheelpicker.widget.TimeWheelLayout
            android:layout_width="200dp"
            android:layout_height="150dp"
            android:layout_gravity="center_horizontal"
            app:wheel_cyclicEnabled="true"
            app:wheel_itemTextSize="10dp"
            app:wheel_itemTextSizeSelected="12dp"
            app:wheel_timeMode="hour_24_has_second"
            app:wheel_visibleItemCount="5" />
```

https://user-images.githubusercontent.com/16816717/146348413-0881a6d6-d7f2-4539-8332-97f649aaa320.mp4

**Comment by liyujiang-gzu** [comment]
@xiaoyaobai See version [4.1.6](https://jitpack.io/#gzu-liyujiang/AndroidPicker/4.1.6)

**Comment by xiaoyaobai** [comment]
> @xiaoyaobai See version [4.1.6](https://jitpack.io/#gzu-liyujiang/AndroidPicker/4.1.6)

emmm，最近有点忙碌没有注意到您回复的消息。实在抱歉。刚刚我试了试4.16错误已经修改。
