### ISSUE TITLE
省市区县乡镇4级联动怎么做呢？

### ISSUE THREAD

**Issue by panyy** [gzu-liyujiang/AndroidPicker#287]

**Comment by liyujiang-gzu** [comment]
目前只支持“省/市/区县”、“省/市”及“市/区县”，含“乡镇”的4级联动，可以参阅AdressPicker的写法。

**Comment by xiangyuecn** [comment]
要支持乡镇级需要先修改Java源码，china_address.json可以参考 #332 更新获取到最新版的省市区数据，并带上乡镇级区划

建议开发当天转换得到新文件，这样就能使用到最新版本数据，所使用的数据源是我的开源库 https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov ，基本上月更，除了省市区乡镇四级区划外，还有坐标边界数据。欢迎用 #332 的代码在线转成china_address.json
