### ISSUE TITLE
日历选择器怎么改成左右翻页？

### ISSUE THREAD

**Issue by palorotolo** [gzu-liyujiang/AndroidPicker#288]
类似 viewpager 的那种。按钮左右切换月份。

**Comment by liyujiang-gzu** [comment]
viewpager 的那种左右切换月份，改动会比较大。将CalendarView中的androidx.recyclerview.widget.RecyclerView改为androidx.viewpager2.widget.ViewPager2可能会小一些，毕竟ViewPager2是基于RecyclerView的。

**Comment by palorotolo** [comment]
```
val calendarView = CalendarView(requireContext())
            val minDate = Date(System.currentTimeMillis())
            val calendar = DateUtils.calendar(minDate)
            calendar.add(Calendar.MONTH, 3)
            val maxDate = calendar.time
            RecyclerView(requireContext()).adapter = calendarView.adapter
            calendarView.adapter
                .notify(false)
                .single(false)
                .valid(minDate, maxDate)
                .intervalNotes("开始", "结束")
                .select(minDate.time, minDate.time)
                .range(minDate, maxDate)
                .refresh()
            val dateSelectionList = contentView.findViewById<RecyclerView>(R.id.dateSelectionList)
            dateSelectionList.layoutManager =
                LinearLayoutManager(requireContext(), RecyclerView.HORIZONTAL, false)
            PagerSnapHelper().attachToRecyclerView(dateSelectionList)
            dateSelectionList.adapter = calendarView.adapter
```
这样写差不多实现了。

**Comment by liyujiang-gzu** [comment]
> ```
> val calendarView = CalendarView(requireContext())
>             val minDate = Date(System.currentTimeMillis())
>             val calendar = DateUtils.calendar(minDate)
>             calendar.add(Calendar.MONTH, 3)
>             val maxDate = calendar.time
>             RecyclerView(requireContext()).adapter = calendarView.adapter
>             calendarView.adapter
>                 .notify(false)
>                 .single(false)
>                 .valid(minDate, maxDate)
>                 .intervalNotes("开始", "结束")
>                 .select(minDate.time, minDate.time)
>                 .range(minDate, maxDate)
>                 .refresh()
>             val dateSelectionList = contentView.findViewById<RecyclerView>(R.id.dateSelectionList)
>             dateSelectionList.layoutManager =
>                 LinearLayoutManager(requireContext(), RecyclerView.HORIZONTAL, false)
>             PagerSnapHelper().attachToRecyclerView(dateSelectionList)
>             dateSelectionList.adapter = calendarView.adapter
> ```
> 
> 这样写差不多实现了。

思路很新奇啊，把竖向的改为横行的

**Comment by palorotolo** [comment]
但还是不完美，不方便监听当前月份的变化。在改别的日历框架。

**Comment by liyujiang-gzu** [comment]
> PagerSnapHelper().attachToRecyclerView(dateSelectionList)

你再用`RecyclerView`来重新包装目测是多于的，可以通过`calendarView.getBodyView()`获取到`RecyclerView`。

**Comment by liyujiang-gzu** [comment]
> PagerSnapHelper().attachToRecyclerView(dateSelectionList)

你再用`RecyclerView`来重新包装目测是多于的，可以通过`calendarView.getBodyView()`获取到`RecyclerView`。
```java
        RecyclerView bodyView = calendarView.getBodyView();
        bodyView.setLayoutManager(new LinearLayoutManager(getContext(), RecyclerView.HORIZONTAL, false));
        new PagerSnapHelper().attachToRecyclerView(bodyView);
```

**Comment by liyujiang-gzu** [comment]
> 但还是不完美，不方便监听当前月份的变化。在改别的日历框架。

不用RecyclerView来重新包装，直接获取CalendarView自带的RecyclerView，应该也就不存在不方便监听当前月份变化的问题了

**Comment by liyujiang-gzu** [comment]
> > 但还是不完美，不方便监听当前月份的变化。在改别的日历框架。
> 
> 不用RecyclerView来重新包装，直接获取CalendarView自带的RecyclerView，应该也就不存在不方便监听当前月份变化的问题了

```java
        CalendarPicker picker = new CalendarPicker(this);
        picker.setRangeDateOnFuture(3);
        picker.setFestivalProvider(new MyFestivalProvider());
        picker.setOnSingleDatePickListener(new OnSingleDatePickListener() {
            @Override
            public void onSingleDatePicked(@NonNull Date date) {
                singleTimeInMillis = date.getTime();
                Toast.makeText(getApplicationContext(), DateFormat.getDateTimeInstance().format(date), Toast.LENGTH_SHORT).show();
            }
        });
        picker.show();
        RecyclerView bodyView = picker.getCalendarView().getBodyView();
        picker.setHeight(bodyView.getHeight());
        bodyView.setLayoutManager(new LinearLayoutManager(this, RecyclerView.HORIZONTAL, false));
        new PagerSnapHelper().attachToRecyclerView(bodyView);
```
