### ISSUE TITLE
使用年月选择器时，应用异常退出

### ISSUE THREAD

**Issue by Tong-c** [gzu-liyujiang/AndroidPicker#29]
之前使用时一切正常，但是今天日志就一直提示下面的错误信息，后来将DateTimePicker类中的StringToYearMonthDay方法返回语句----Integer.parseInt(text)给try-catch起来，程序可继续执行，应用也不再退出
异常信息如下：
<img width="763" alt="default" src="https://cloud.githubusercontent.com/assets/14778144/17055317/992d217e-503e-11e6-8fc9-eeb088a095e7.png">

**Comment by liyujiang-gzu** [comment]
v1.2.1已修复
