### ISSUE TITLE
日历范围选择器

### ISSUE THREAD

**Issue by YQcharlse** [gzu-liyujiang/AndroidPicker#290]
你好，有一个问题，就是我的日期范围是去年到今天的，但是在选择范围的时候，会记录上次选择的范围，每次赋值默认选择的日期范围，选择有1号的时候 ，打开没有跳转到当前选择的范围，而是到了开始的日期。

**Comment by chen2tu** [comment]
同样碰到了，问题原因是：
CalendarAdapter 中，getDatePosition 方法的
`        for (int i = 0; i <= lastPosition; i++) {
            Calendar minDate = DateUtils.calendar(dates.get(i).getTime());
            minDate.set(Calendar.DAY_OF_MONTH, 1);
            minDate.set(Calendar.HOUR_OF_DAY, 0);
            minDate.set(Calendar.MINUTE, 0);
            minDate.set(Calendar.SECOND, 0);
            Calendar maxDate = DateUtils.calendar(dates.get(i).getTime());
            maxDate.set(Calendar.DAY_OF_MONTH, DateUtils.maxDaysOfMonth(maxDate.getTime()));
            maxDate.set(Calendar.HOUR_OF_DAY, 23);
            maxDate.set(Calendar.MINUTE, 59);
            maxDate.set(Calendar.SECOND, 59);
            if (time >= minDate.getTime().getTime() && time <= maxDate.getTime().getTime()) {
                return i;
            }
        }`

代码中算法有问题。

如果不想拉代码下来修改的话，使用者在设置日历回显的时候，startDate + 1000ms 就可以规避这个问题了。

**Comment by YQcharlse** [comment]
好的谢谢。

**Comment by hexin9456** [comment]
> 
你好 问一下 设置回显是哪个方法呢？使用的是CalendarPicker
