### ISSUE TITLE
com.github.gzuliyujiang.filepicker.FileExplorer显示有点卡顿

### ISSUE THREAD

**Issue by Reginer** [gzu-liyujiang/AndroidPicker#293]
可否改成异步加载？有这个控件的页面启动速度会变慢

**Comment by liyujiang-gzu** [comment]
用的是直接同步读取文件目录及文件列表，若某个目录下文件过多，肯定是偶遇影响速度的。异步加载是需要改下源代码`FileAdapter#loadData(String initDir)`。
![微信截图_20220316104827](https://user-images.githubusercontent.com/16816717/158506802-b248ecf3-0bbc-43ea-8358-1cd04ed3f0ba.png)

**Comment by Reginer** [comment]
嗯是的，有打算更新的话可否把这个一起更新上去

**Comment by liyujiang-gzu** [comment]
> 嗯是的，有打算更新的话可否把这个一起更新上去

正在尝试修改中

**Comment by liyujiang-gzu** [comment]
@Reginer 使用这个临时版本试试：` implementation 'com.github.gzu-liyujiang.AndroidPicker:FilePicker:4621549e35`

**Comment by Reginer** [comment]
```
java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:244)
	at com.github.gzuliyujiang.filepicker.adapter.FileAdapter.loadData(FileAdapter.java:297)
	at com.github.gzuliyujiang.filepicker.FileExplorer.refreshCurrent(FileExplorer.java:207)
	at com.github.gzuliyujiang.filepicker.FileExplorer.onPathClicked(FileExplorer.java:137)
	at com.github.gzuliyujiang.filepicker.adapter.PathAdapter$1.onClick(PathAdapter.java:102)
```
说一下我的操作，是在DialogFragment里显示这个控件的。

第一次显示正常的，DialogFragment.show -> DialogFragment.dismiss

第二次打开就开始异常了，会把本来取消显示的home和back显示出来

多次显示取消之后，点击上面目录快捷位置会崩溃

**Comment by liyujiang-gzu** [comment]
NoSuchElementException...LinkedList.getFirst...目测是多线程数据同步问题导致LinkedList.isEmpty判断失效。LinkedList不是线程安全的。

**Comment by liyujiang-gzu** [comment]
@Reginer 我demo的场景，用LinkedList和ConcurrentLinkedQueue都没有闪退，我重新换成ConcurrentLinkedQueue实现你再试试： `implementation 'com.github.gzu-liyujiang.AndroidPicker:FilePicker:d56b38e068`

**Comment by Reginer** [comment]
崩溃没有了，上面流程会复现出来目录显示不全问题，就显示一个文件夹，单击文件夹跳转到了一个错误的文件夹
还会有把本来设置隐藏的home和back显示出来

**Comment by Reginer** [comment]
![bug复现](https://user-images.githubusercontent.com/12568257/158551437-b97470bb-d78f-488e-bd97-394adfb6ec1f.png)

修改了几个文件可以复现我说的问题，把这个图片保存下来，后缀名修改为zip，里面有个bug复现.patch文件，合并到现在的源码里就可以复现点那个弹窗浏览就可以复现问题了。

**Comment by Reginer** [comment]
> ![bug复现](https://user-images.githubusercontent.com/12568257/158551437-b97470bb-d78f-488e-bd97-394adfb6ec1f.png)
> 
> 修改了几个文件可以复现我说的问题，把这个图片保存下来，后缀名修改为zip，里面有个bug复现.patch文件，合并到现在的源码里就可以复现点那个弹窗浏览就可以复现问题了。

哦，太不幸了，github把图片压缩了，里面压缩包解压不出来了，补丁发到你qq邮箱了

**Comment by Reginer** [comment]
bug做了下修复,修改方法    `com.github.gzuliyujiang.filepicker.adapter.FileAdapter#loadData`
```
public void loadData(final File dir) {
        if (!loadAsync) {
            reallyRefresh(loadDataSync(dir));
        } else {
            THREAD_POOL.execute(new Runnable() {
                @Override
                public void run() {
                    final List<FileEntity> temp = loadDataSync(dir);
                    UI_HANDLER.post(new Runnable() {
                        @Override
                        public void run() {
                            reallyRefresh(temp);
                        }
                    });
                }
            });
        }

    }
```

调用的时候，setInitDir方法最后调用

```

        fileExplorer.setShowHomeDir(false);
        fileExplorer.setShowUpDir(false);
        fileExplorer.setShowHideDir(false);
        fileExplorer.setInitDir(ExplorerMode.FILE, new File("sdcard"),true);
```

**Comment by liyujiang-gzu** [comment]
你最后改的这个是我最开始的写法，这种写法有一个问题，就是：上一个目录数据还未加载出来就快速切换目录，这样会造成数据刷新混乱。所以我才改成队列的方式……

**Comment by liyujiang-gzu** [comment]
@Reginer FileExplorer已重构
