### ISSUE TITLE
能否实现时间循环滑动

### ISSUE THREAD

**Issue by huangwm1984** [gzu-liyujiang/AndroidPicker#3]
目前比如时间滑到59分就不可再滑动，能否实现时间循环滑动，滑动到59分下面又有00，01，02如此等等。

**Comment by gzu-liyujiang** [comment]
谢谢建议，我尝试改改

**Comment by gzu-liyujiang** [comment]
v1.0.3已经支持伪循环滑动。如：滑动到59分继续向上滑动会跳到00，滑动到00分继续向下滑动会跳到59，

**Comment by palorotolo** [comment]
> v1.0.3已经支持伪循环滑动。如：滑动到59分继续向上滑动会跳到00，滑动到00分继续向下滑动会跳到59，

API 是哪个？

**Comment by liyujiang-gzu** [comment]
> > v1.0.3已经支持伪循环滑动。如：滑动到59分继续向上滑动会跳到00，滑动到00分继续向下滑动会跳到59，
> 
> API 是哪个？

3.x之后的版本：
picker.getWheelLayout().setCyclicEnabled(true)
