### ISSUE TITLE
可否引入街道数据

### ISSUE THREAD

**Issue by ysmintor** [gzu-liyujiang/AndroidPicker#30]
### 街道数据

省市区都提供了，可不可以再提供街道数据包括areacode，这样的话基本直接引入了。另外如何当一打开后选择到对应的省市区地址呢？

**Comment by liyujiang-gzu** [comment]
我没得街道数据。一打开后选择到对应的省市区地址:
```java
picker.setSelectedItem("贵州", "贵阳", "花溪");
```

**Comment by liyujiang-gzu** [comment]
前几天我找到了个含有街道数据的SQLite数据库area.db，已收入demo的assets目录下，以备后用
