### ISSUE TITLE
picker内数据过多时，显示会延迟。

### ISSUE THREAD

**Issue by Hankay** [gzu-liyujiang/AndroidPicker#31]
看了源码，数据是一次加载的，不知可不可以分页加载数据。

**Comment by liyujiang-gzu** [comment]
分页加载需要自己改，demo是一次性加载

**Comment by liyujiang-gzu** [comment]
可以尝试[realm-java](https://github.com/realm/realm-java)这个据说比SQLite高效的NoSQL数据库realm的类库，从json读取数据……

**Comment by liyujiang-gzu** [comment]
1.5.X版本改进了很多
