### ISSUE TITLE
无法选择2022-07-01，02，03

### ISSUE THREAD

**Issue by zabio** [gzu-liyujiang/AndroidPicker#311]
今天2022-07-04号 无法选择01，02，03

**Comment by zabio** [comment]
DateWheelLayout#changeDay()
 //开始年月及结束年月相同情况
这段逻辑min的赋值有问题

**Comment by liyujiang-gzu** [comment]
> 今天2022-07-04号 无法选择01，02，03

你设置的可选择范围是多少呢？默认是从今天往后

**Comment by zabio** [comment]
#bug 当日是7月4号       ，测试的时候可以把手机时间设置为2022年7月4号  
        //三年前
          val g = GregorianCalendar()
          g.add(Calendar.YEAR, -3)
          val minDate = DateEntity.target(g)
          //今天
          val maxDate = DateEntity.today()

          val picker = DatePicker(this).apply {

              val colorBlue = getColorCompat(R.color.c_t_blue)
              wheelLayout.apply {
                  setDateMode(DateMode.YEAR_MONTH_DAY)
                  setDateFormatter(UnitDateFormatter())
                  setTextColor(getColorCompat(R.color.c_t_black))
                  setSelectedTextColor(colorBlue)
                  //setIndicatorColor(getColor(R.color.c_t_blue))
                  setVisibleItemCount(8)
                  setCurtainRadius(0.1f)
                  setItemSpace(32)
                  setCurvedEnabled(true)
                  setCurvedIndicatorSpace(20)
                  //setCyclicEnabled(true)
                  setRange(minDate, maxDate)
              }
              val block: (tv: TextView) -> Unit = {
                  it.setTextColor(colorBlue)
                  it.typeface = Typeface.defaultFromStyle(Typeface.BOLD)
              }
              block.invoke(okView)
              block.invoke(cancelView)
          }

**Comment by zabio** [comment]
不设置range会导致这个问题

**Comment by zabio** [comment]
设置range就可以了，已解决
