### ISSUE TITLE
弹出框的位置可否改变？

### ISSUE THREAD

**Issue by 897902334** [gzu-liyujiang/AndroidPicker#33]
大神，你的这个demo弹出框必须是在底部出现吗？不能设置成中间或者上方显示吗？？？

**Comment by liyujiang-gzu** [comment]
改显示位置需要修改源代码：Popup.java。构造函数里有一个Gravity.Bottom

**Comment by liyujiang-gzu** [comment]
增强选择器可指定弹框显示位置(参见demo的第二例)
