### ISSUE TITLE
圆角和样式

### ISSUE THREAD

**Issue by yishangfei** [gzu-liyujiang/AndroidPicker#338]
![image](https://github.com/gzu-liyujiang/AndroidPicker/assets/15099278/16789f13-b57e-46b6-89b0-40d884a0c695)

想问一下怎么想图片这样呢
   app:wheel_curtainRadius="8dp"
   app:wheel_curtainCorner="all"
这两个会导致小时和分钟都会有圆角

上下午貌似找的配置都是在右边

**Comment by liyujiang-gzu** [comment]
@yishangfei 参阅demo中的地址选择器，关键代码如下（`getWheel#setCurtainRadius`、`getWheelView#setCurtainCorner`）：
```java
...
        LinkageWheelLayout wheelLayout = picker.getWheelLayout();
        wheelLayout.setCurtainEnabled(true);
        wheelLayout.setCurtainColor(0xFF22EEFF);
        wheelLayout.setCurtainRadius(8 * view.getResources().getDisplayMetrics().density);
        picker.getProvinceWheelView().setCurtainCorner(CurtainCorner.LEFT);
        picker.getCityWheelView().setCurtainCorner(CurtainCorner.RIGHT);
```
![image](https://github.com/gzu-liyujiang/AndroidPicker/assets/16816717/afb60c33-f2c3-4e34-83a1-260b81cc1a7b)
