### ISSUE TITLE
虚拟按键的手机，弹窗弹出的位置在虚拟按钮之下

### ISSUE THREAD

**Issue by zouxianbincc** [gzu-liyujiang/AndroidPicker#38]
虚拟按键的手机，弹窗弹出的位置在虚拟按钮之下，被虚拟按键挡住了。这个怎么解决？

**Comment by zouxianbincc** [comment]
我设置了android:fitsSystemWindows="true"

**Comment by zouxianbincc** [comment]
下载了原码，看了一下。原来这个弹窗并不是基于项目本身的视图。 而是新new 了一个dialog 获取的 window . 所以 在自己项目中如果设置了全透明主题时，或是沉浸式状态 菜单时，最 把原码下下来。在
Common 包下 Popup类中 init 方法里 ，对 contentLayout = new FrameLayout(context); 设置一下contentLayout.setFitsSystemWindows(true);问题就解决了

**Comment by catroom** [comment]
<item name="android:windowTranslucentNavigation">false</item>//适配华为手机的虚拟按键

不要沉浸虚拟按键。一般人都找不到这个方法。贡献给这位兄弟了

**Comment by liyujiang-gzu** [comment]
华为手机绝大部分都是虚拟按键，可以沉浸顶部标题栏，但不要沉浸底部导航栏？

**Comment by liyujiang-gzu** [comment]
可以沉浸顶部标题栏：
        window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);//通知状态栏半透明
但不要沉浸底部导航栏：
        ~~window.addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION);//通知状态栏半透明~~
