### ISSUE TITLE
搜索依赖里面找不到你的andoridPicker

### ISSUE THREAD

**Issue by ZengHongHua** [gzu-liyujiang/AndroidPicker#4]
在Project Structure 里面搜索你的AndroidPicker 依赖找不到,
gradle文件里面添加 compile 'cn.qqtheme.framework:AndroidPicker:latest.integration'  是没问题..

**Comment by ZengHongHua** [comment]
还有现在,把你项目下下来,会出现 :Error:Connection refused: connect
是不是你提交了一些不用提交的,我这构建不了....

**Comment by gzu-liyujiang** [comment]
刚学习发布项目到jcenter，还不太熟悉。好像在Project Structure 里面搜索的是Maven Central而不是jcenter。   

Error:Connection refused: connect，估计是我改了gradle-wrapper.properties造成的：
```
#distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-all.zip
distributionUrl=http://127.0.0.1/php-develop/gradle-2.8-all.zip
```
你去掉127.0.0.1这行，还原services.gradle.org试试
