### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Arisono** [gzu-liyujiang/AndroidPicker#40]
1 日期选择添加扩展：年月日 时分秒  展示
2  wheel滚动时候有视觉效果，类似ios

**Comment by liyujiang-gzu** [comment]
谢谢建议，由于我水平有限，wheel滚动时候有类似ios的视觉效果，这个不好办

**Comment by liyujiang-gzu** [comment]
1.5.X版本已经类似ios的视觉效果，已经支持年月日时分选择器（不支持秒）
