### ISSUE TITLE
城市选择

### ISSUE THREAD

**Issue by cableyang** [gzu-liyujiang/AndroidPicker#43]
直辖市 选择时候按照name 选择有些不便，希望能够通过id回调

**Comment by liyujiang-gzu** [comment]
id回调指的是？不太理解你说的id回调。现在最新版回调返回的是城市的实体类，包含了城市名、城市编号，可以扩展Area类，让实体类携带更多的属性。

**Comment by liyujiang-gzu** [comment]
1.5.X版本已经支持传入对象
