### ISSUE TITLE
自动构建的提议

### ISSUE THREAD

**Issue by msdx** [gzu-liyujiang/AndroidPicker#46]
@gzu-liyujiang 我有一个提议：
添加travis-ci脚本，当有代码推上来时可自动构建并发布到fir。其他人可直接从fir.im上下载最新版本apk进行体验。参见：https://github.com/msdx/gradle-doc-apk

另外，即使不推到fir.im，也可以用travis-ci 自动构建进行编译，当其他人提交代码时，能够检查是否编译通过，如果有编写测试用例，也可以知道是否测试通过。

**Comment by hezhipengzipp** [comment]
尼玛  这个自动构建好复杂呀，下载源代码也是好多问题

**Comment by msdx** [comment]
你想多了。

**Comment by msdx** [comment]
不，只需要添加一个yml，然后在travis-ci.org上导入即可。

**Comment by hezhipengzipp** [comment]
你扣扣号多少 我加下你  导入失败

**Comment by msdx** [comment]
@hezhipengzipp 步骤如下：

1. 用github账号登录travis-ci.org
2. 同步账号，把github上的项目同步过来
3. 开启该项目的travis-ci构建
4. 为你的项目添加.travis-ci.yml文件
5. 推送到github，以触发它的构建。

.travis-ci.yml 可参考：https://github.com/msdx/AndroidPicker/tree/travis-ci

**Comment by liyujiang-gzu** [comment]
谢谢，这个之前我未曾接触过，学习了，下班试试看

**Comment by liyujiang-gzu** [comment]
已合入
