### ISSUE TITLE
日期选择器setSelectedItem后显示有误

### ISSUE THREAD

**Issue by ChiLogNNS** [gzu-liyujiang/AndroidPicker#50]
datePicker.setSelectedItem(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH)+1, calendar.get(Calendar.DAY_OF_MONTH));

这样设置后显示选中的月份总是1月

**Comment by liyujiang-gzu** [comment]
这个问题@msdx在#44已经修复，只不过最新源代码还未来得及打包推送到jcenter

**Comment by liyujiang-gzu** [comment]
v1.2.3已修正
