### ISSUE TITLE
功能性建议

### ISSUE THREAD

**Issue by mengzhihoing** [gzu-liyujiang/AndroidPicker#53]
1.前面有人提到了弹出框的位置，这是一个问题，能不能直接在布局文件里布局？
2.能不能滑动结束的时候就获取值（比如年月日）而不需要点击确定之后才可以获取。
3.以上两条结合起来就是：位置可以自定、滑动结束可以获取值，点击隐藏“确定”“取消按钮”。

如果可以的话，那就很强大了，谢谢。

**Comment by liyujiang-gzu** [comment]
谢谢建议。
现在位置已经可以自定的，方法为：picker.setGravity()。滑动结束就有值了，不知道你的应用场景是啥，可以调用方法：picker.getSelectedXXX()，点击确定是触发条件。

**Comment by mengzhihoing** [comment]
@liyujiang-gzu 谢谢

**Comment by liyujiang-gzu** [comment]
1.5.X版本都已经支持，详见demo
