### ISSUE TITLE
刚弹出日期选择时，滚动年份，月份和日都自动变成1

### ISSUE THREAD

**Issue by mengzhihoing** [gzu-liyujiang/AndroidPicker#54]
比如设定开始日期为2016-10-08日，点击按钮弹出日期选择器，然后滚动年份，这时，变成xxxx-01-01,为什么会这样？故意设定的吗？我觉得除非是平年的2月29日（自动改为28），否则月份和日应该不会自动修正。谢谢作者开发这么好的项目。

**Comment by liyujiang-gzu** [comment]
最新源代码已经修改了这个问题，不过还未来得及发不到jcenter

**Comment by liyujiang-gzu** [comment]
v1.2.3已修正
