### ISSUE TITLE
您好,请问单项选择里OptionPicker,上面的Top可不可以自定义高度?

### ISSUE THREAD

**Issue by LiysCAO** [gzu-liyujiang/AndroidPicker#56]
代码里已经有自定义Top的背景颜色,picker.setTopBackgroundColor(Color.parseColor("#6699ff"));
那么是否可以添加上自定义高度呢,如果设置下面的Item字体稍微大一些的,就会显得上面的头很不协调,建议添加Top的确认的setSubmitTextSize(),取消的setCancelTextSize(),标题的 picker.setTitleTextSize();
和Top的高度setTopHight();
最后谢谢您的共享....

**Comment by liyujiang-gzu** [comment]
谢谢建议，有空改下

**Comment by liyujiang-gzu** [comment]
v1.2.3已支持
