### ISSUE TITLE
二三级联动时，想让某个列的宽度自定义宽一些，使数据能尽可能的不尾部省略

### ISSUE THREAD

**Issue by xiphodon** [gzu-liyujiang/AndroidPicker#57]
二三级联动时，想让某个列的宽度自定义宽一些，使每条数据能尽可能的不尾部省略

**Comment by liyujiang-gzu** [comment]
列表项数据过长显示不完，尾部省略，目前是使用**picker.setTextSize**来设置尽可能合适的字号，这个我还没想到好的解决办法

**Comment by xiphodon** [comment]
初始化控件的时候把控件显示的各列宽度比例暴露出来，默认1:1或1:1:1平分屏幕宽，可以在构造时候传递自定义宽度比例，不知道是否方便实现，感谢你的分享~~

**Comment by liyujiang-gzu** [comment]
暴露各列宽比例，这个不错，目前是1:1，文字少的列是浪费了点空间，有的是可以设成1:2显示更佳，有空我会改下

**Comment by liyujiang-gzu** [comment]
```java
picker.setColumnWeight(1/3.0, 2/3.0);//比例为1:2
```
```java
picker.setColumnWeight(2/8.0, 3/8.0, 3/8.0);//省级、地级和县级的比例为2:3:3
```

**Comment by xiphodon** [comment]
这真是太棒了，感谢你的分享
