### ISSUE TITLE
功能建议：DateTimePicker里能有setRangeStart()方法，具体到分钟

### ISSUE THREAD

**Issue by yuwenb** [gzu-liyujiang/AndroidPicker#58]
TimePicker，DatePicker的区间设定分别是分钟和天，但是DateTimePicker的区间设定只能设定到年，根据这个命名，DateTimePicker区间设定应该是到分钟?

**Comment by liyujiang-gzu** [comment]
DateTimePicker是之前的某个兄弟将TimePicker和DatePicker结合在一起的，代码有点多，我还没改DateTimePicker的日期时间区间限定。

**Comment by liyujiang-gzu** [comment]
DateTimePicker同TimePicker、DatePicker的绝大部分代码是重复的，不科学。以前我没考虑日期时间同时选择的情况，故而分成TimePicker和DatePicker，后来发现很多兄弟有日期时间同时选择的需求，@dongzhaoqi才加入了DateTimePicker。理论上DateTimePicker、TimePicker、DatePicker应该合并为一个，需要重构一下，不然同时维护DateTimePicker同TimePicker、DatePicker比较麻烦……

**Comment by yuwenb** [comment]
之前我也想着改源码，发现导入项目搞不定。。。。。。

**Comment by liyujiang-gzu** [comment]
1.3.4后重构DateTimePicker，支持setDateRangeStart()、setTimeRangeStart()等方法，具体到分钟
