### ISSUE TITLE
只要省级、地级怎么设置呢？

### ISSUE THREAD

**Issue by fangood** [gzu-liyujiang/AndroidPicker#6]
如题

**Comment by liyujiang-gzu** [comment]
原理和只要地级、县级是一样的，在“makeCenterView()”里加个条件判断，设置县级那个countyView为GONE，然后JSON数据里的县级数据置为“{}”（闲麻烦的话，也可以直接用city.json那个）

**Comment by fangood** [comment]
谢谢，稍后测试下

发自我的 iPhone

**Comment by ZengHongHua** [comment]
求暴露一个只要省级,低级的方法

**Comment by liyujiang-gzu** [comment]
新增只选择省和市的picker #9，感谢@venusic
