### ISSUE TITLE
使用LinkagePicker（我只用到了一二级Picker）时会触发java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pwj1568** [gzu-liyujiang/AndroidPicker#60]
demo中提供的例子也有这个bug。其中地址选择（只包括地级、县级）那一项很容易就引发这个bug。
当一级picker的选中项为第一项时，同时二级picker的选中项不为第一项时，这个时候迅速向下滑动一级picker，百分之九十都会引发java.lang.IndexOutOfBoundsException.

**Comment by liyujiang-gzu** [comment]
刚刚已经修复 [9c0f27e](https://github.com/gzu-liyujiang/AndroidPicker/commit/9c0f27e73fd7c77c2c937cdc71a214b59d786161)
