### ISSUE TITLE
日期选择

### ISSUE THREAD

**Issue by mengzhihoing** [gzu-liyujiang/AndroidPicker#61]
刚弹出选择器时，滚动年份，月份不会自动为1（之前自动为1），但是日却自动为1.是我打开的方式不对吗。

**Comment by liyujiang-gzu** [comment]
昨天改了点逻辑，不是特殊情况的话，上一次选择的月份是多少滚动年份后还是多少，不再自动为1.不知道这样的逻辑是否合理？

**Comment by mengzhihoing** [comment]
@liyujiang-gzu 完全合理 ！！厉害！多谢。

**Comment by mengzhihoing** [comment]
@liyujiang-gzu 跪求提交至jcenter，本地不会弄。

**Comment by liyujiang-gzu** [comment]
已经提交了的呀，1.2.4。jcenter和jitpack都有

**Comment by mengzhihoing** [comment]
@liyujiang-gzu 
[https://raw.githubusercontent.com/mengzhihoing/md/master/hh.png](url)  
[https://raw.githubusercontent.com/mengzhihoing/md/master/meng.gif](url)

**Comment by liyujiang-gzu** [comment]
上面你这个截图，是因为年月日范围限制，逻辑是比较复杂，2016.8.29-2022.1.1，中间索引及值做了很多处理

**Comment by liyujiang-gzu** [comment]
由于范围限制，又是三级联动，日子的逻辑可能还有点问题。。。

**Comment by mengzhihoing** [comment]
@liyujiang-gzu 好的，感谢。
