### ISSUE TITLE
国际化处理

### ISSUE THREAD

**Issue by LitbLeo** [gzu-liyujiang/AndroidPicker#62]
建议做一下国际化处理，如英文、中文等语言！

**Comment by liyujiang-gzu** [comment]
谢谢您的建议，有空再重构吧！
我原以为这种控件中国味比较浓，当初就没怎么考虑国际化语言。不过，应该可以通过选择器提供的各种**setXXXText**以及**setLabel**来实现多语言的，通过**context.getString(R.string.xxx)**得到……

**Comment by wuzhaohui026** [comment]
是可以把显示的文字设置为英文的是吧

**Comment by liyujiang-gzu** [comment]
是的，调用选择器提供的各种setXXXText以及setLabel，通过context.getString(R.string.xxx)得到多国语言

**Comment by liyujiang-gzu** [comment]
新更新的demo里的星座选择器就是多语言的例子，包括英文及中文。
