### ISSUE TITLE
渲染过慢

### ISSUE THREAD

**Issue by HeCaser** [gzu-liyujiang/AndroidPicker#64]
在一些低端机上,比如小米1会出现弹出很慢的现象

**Comment by liyujiang-gzu** [comment]
额，弹框框架里的View的初始化过程有点绕，还有改进的空间

**Comment by liyujiang-gzu** [comment]
动态根据选项数创建view，选项越多创建的view越多，未作对象复用处理，大批量数据会比较慢，只适合少量的数据选择，如性别选择、职业选择、学历选择等

**Comment by liyujiang-gzu** [comment]
1.4.x版本重构基于ListView来实现，大批量数据时效率高很多
