### ISSUE TITLE
能否加入对float或者double的支持？

### ISSUE THREAD

**Issue by MoonlightSW** [gzu-liyujiang/AndroidPicker#72]
有些特殊情况还是需要使用float或者double型的数据，比如温度，能添加吗？

**Comment by liyujiang-gzu** [comment]
是可以添加的，类似于NumberPicker，应该完全可以继承自OptionPicker来实现

**Comment by MoonlightSW** [comment]
是的我用OptionPicker实现了。但是很麻烦需要用String[]数组，然后用的时候还需要再转换回来，头疼，不知道能不能搞的方便一点，类似NumberPicker指定范围就好了，不然还得自己写String[]数组转换

**Comment by liyujiang-gzu** [comment]
你的小数是怎么递增的？0.5一个递增量么？

建议不直接用OptionPicker，使用继承的方式，具体你参考下NumberPicker的实现方式。

**Comment by liyujiang-gzu** [comment]
一定要充分利用继承的特性，就可以不用进行数组转换了

**Comment by MoonlightSW** [comment]
我的是0.1，你说的对，我可以自己继承写一个~thx

**Comment by liyujiang-gzu** [comment]
1.3.*的NumberPicker已支持浮点型

**Comment by MoonlightSW** [comment]
会玩儿！赞一个~
