### ISSUE TITLE
picker.setOnOptionPickListener方法不能用了吗？？

### ISSUE THREAD

**Issue by YYwishp** [gzu-liyujiang/AndroidPicker#73]
您好，之前使用了您的项目中一些控件，关于单项选择的，其中用到了picker.setOnOptionPickListener（）这个方法，但是今天一打开项目，就开始报错，说找不到这个方法，麻烦请问下，是不是这个方法没有了？？（我是直接在gradle中添加的依赖）

**Comment by liyujiang-gzu** [comment]
能用的，只是方法名改了，重构提取了一个父类Single
Picker，接口里的方法onOptionPicked变成onItemPicked了

**Comment by liyujiang-gzu** [comment]
OnOptionPickListener改成了抽象类

**Comment by liyujiang-gzu** [comment]
public static abstract class OnOptionPickListener implements OnItemPickListener<String> {

        public abstract void onOptionPicked(int index, String item);

        @Override
        public final void onItemPicked(int index, String item) {
            onOptionPicked(index, item);
        }

    }

**Comment by liyujiang-gzu** [comment]
是因为1.3.0版本重构了OptionPicker和NumberPicker，改了方法名称，1.3.2已做兼容处理：
```java
    public void setOnNumberPickListener(OnNumberPickListener listener) {
        super.setOnItemPickListener(listener);
    }

    /**
     * @deprecated use {@link #setOnNumberPickListener(OnNumberPickListener)} instead
     */
    @Deprecated
    public void setOnOptionPickListener(final OptionPicker.OnOptionPickListener listener) {
        setOnNumberPickListener(new OnNumberPickListener() {
            @Override
            public void onNumberPicked(int index, Number item) {
                listener.onOptionPicked(index, item.toString());
            }
        });
    }
```
