### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by fangx** [gzu-liyujiang/AndroidPicker#77]
控件非常好用，使用的时候有两个小问题，希望作者更新啊~
1.时间选择如果设置WheelView.LineConfig就会出现如图情况，希望可以处理下
2.顶部确认和取消按钮是否可以更靠近两边一些，感觉那样更好看，左右padding有点大，或者可以开放个方法设置这个间距。
感谢作者写出这么好用的轮子~
<img width="349" alt="fe8dc4fd-d38b-4907-a66a-aa01303668a8" src="https://cloud.githubusercontent.com/assets/5337466/21558787/9193211a-ce7a-11e6-8d39-d33d61f61beb.png">

**Comment by liyujiang-gzu** [comment]
谢谢你的建议，顶部按钮的边距默认是10dp，你这个效果的确大点了，稍后开放个padding方法

**Comment by liyujiang-gzu** [comment]
你的年份的分割线长度不够，原因还待分析，我用模拟器和奇酷手机试了是正常的

**Comment by liyujiang-gzu** [comment]
show之后可以通过getTitleView(),getCancelButton(),getSubmitButton() 得到按钮，然后设置想要的属性

**Comment by liyujiang-gzu** [comment]
边距设置方法为：picker.setTopPadding(25)，单位为dp

**Comment by fangx** [comment]
好的，谢谢~

**Comment by fangx** [comment]
貌似两个都还是不行，我看了下布局，好像是textview的宽度的问题，不是padding的问题，line那个好像也还不行

**Comment by fangx** [comment]
<img width="365" alt="6aae5e38-f799-4665-805e-f553dccc6436" src="https://cloud.githubusercontent.com/assets/5337466/21598371/da053e50-d196-11e6-8a30-4fb268988ce3.png">

**Comment by liyujiang-gzu** [comment]
![20170103132316](https://cloud.githubusercontent.com/assets/16816717/21600498/3e5a3bb4-d1b8-11e6-89ff-88e4cd891135.png)
![20170103132724](https://cloud.githubusercontent.com/assets/16816717/21600508/6a93fab2-d1b8-11e6-8f29-3c4919ea9dcb.png)
那按钮是android.widget.Button，设置padding是可以的啊，你的上图是什么工具分析得到的？

**Comment by liyujiang-gzu** [comment]
已知道原因，和设置的默认主题有关，将主题设置为Holo就好了。如：
```java
//setTheme(android.R.style.Theme_Material_Light_NoActionBar);
setTheme(android.R.style.Theme_Holo_Light_NoActionBar);
```
在选择器内部修改ConfirmPopup类的构造函数：
```java
    public ConfirmPopup(Activity activity) {
        super(activity);
        activity.setTheme(android.R.style.Theme_Holo_Light_NoActionBar);
    }
```

**Comment by fangx** [comment]
那个效果是开发者工具里有个显示布局界限的开关，那我现在需要修改activity的Theme还是？

**Comment by liyujiang-gzu** [comment]
顶部按钮的风格自定义，可以通过以下类似的代码实现：
```xml
    <style name="AndroidPicker_CustomTopButton">
        <item name="android:textColor">@android:color/holo_red_dark</item>
        <item name="android:textSize">12sp</item>
        <item name="android:textStyle">bold|italic</item>
        <item name="android:padding">20dp</item>
        <item name="android:minWidth">80dp</item>
    </style>
```
```java
picker.show();
picker.getCancelButton().setTextAppearance(activity, R.style.AndroidPicker_CustomTopButton);
```

**Comment by liyujiang-gzu** [comment]
@fangx 我已修改ConfirmPopup类，稍后提交代码

**Comment by fangx** [comment]
好的，谢谢~

**Comment by fangx** [comment]
现在可以了么，好像库版本没有更新呀~

**Comment by liyujiang-gzu** [comment]
jcenter库和jitpack库还没构建

**Comment by liyujiang-gzu** [comment]
@fangx 1.3.5已发布到jcenter及jitpack'
