### ISSUE TITLE
省市县三级联动数据初始化失败。

### ISSUE THREAD

**Issue by 06304322** [gzu-liyujiang/AndroidPicker#78]
大神我用的是你的demo的方法
new AddressInitTask(this).execute("贵州", "毕节", "纳雍");

city.json也添加了。

**Comment by liyujiang-gzu** [comment]
看logcat，有报什么错么

**Comment by 06304322** [comment]
没有报错。。

**Comment by liyujiang-gzu** [comment]
初始化时估计是有异常的，被try……catch……了，看下控制台的System.err

**Comment by 06304322** [comment]
是这个问题。
System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
System.err:     at com.lianchengit.schoolchat.widget.AddressInitTask.doInBackground(AddressInitTask.java:70)
System.err:     at com.lianchengit.schoolchat.widget.AddressInitTask.doInBackground(AddressInitTask.java:28)
System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by 06304322** [comment]
是这个问题

System.err: java.io.FileNotFoundException: city.json
System.err:     at android.content.res.AssetManager.openAsset(Native Method)
System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
System.err:     at android.content.res.AssetManager.open(AssetManager.java:287)
System.err:     at com.lianchengit.schoolchat.widget.AddressInitTask.doInBackground(AddressInitTask.java:70)
System.err:    at com.lianchengit.schoolchat.widget.AddressInitTask.doInBackground(AddressInitTask.java:28)

**Comment by liyujiang-gzu** [comment]
System.err: java.io.FileNotFoundException: city.json，明显是找不到city.json，你添加的位置对么？放在项目的assets下

**Comment by 06304322** [comment]
![11111111](https://cloud.githubusercontent.com/assets/20898168/21755700/d5489cde-d652-11e6-9944-82d8009e9436.png)
位置是对的吧。

**Comment by liyujiang-gzu** [comment]
/src/main/assets/city.json，这个未知是对的，还是 java.io.FileNotFoundException么？会不会是文件读权限问题？ＡＰＩ　２３＋需要动态申请文件读权限

**Comment by 06304322** [comment]
好像不是权限的问题，如果没有权限的话会报错，况且初始化的时候已经申请了权限。想用这个城市三级联动是不是只需要添加这个类AddressInitTask就可以了？

**Comment by liyujiang-gzu** [comment]
如果没特殊要求，添加demo里的city.json、AddressPickTask即可（新版本已重构AddressInitTask）

**Comment by huangruiLearn** [comment]
找不到啊  同样的问题 @06304322  怎么解决了

**Comment by 06304322** [comment]
你看你的项目里面是不是有重复的assets目录只保留一个。

**Comment by 06304322** [comment]
@huangruiLearn 你看你的项目里面是不是有assets重复的目录，只保留一个。
