### ISSUE TITLE
setSelectedItem 在第二级上不工作

### ISSUE THREAD

**Issue by Mason-Fan** [gzu-liyujiang/AndroidPicker#83]
两级连动的AddressPicker， setSelectedItem 只在省一级管用，在第二级“市”上不管用。
存在问题版本: 1.4.2

**Comment by liyujiang-gzu** [comment]
1.4.*版本重构后使用adapter，对view进行复用，貌似WheelView内部调用setSection时加上postDelay进行延时处理才能保证选中项的准确性

**Comment by asimes520** [comment]
在1.4.2版本中，OptionPicker中在将循环滚动给禁用掉以后设置选中项无效，只有不禁用循环滚动才行。然后是DatePicker中，如果禁用了循环滚动，也会导致二级和三级的选中项无效。再就是AddressPicker中设置的二级和三级选中项无效，1.4.2和1.3.5好像都会有这个问题。

**Comment by liyujiang-gzu** [comment]
1.4.3加了个延时能解决

**Comment by Mason-Fan** [comment]
这个问题会在下一个release中解决么？

**Comment by liyujiang-gzu** [comment]
1.4.3勉强能解决，不过效果不太好。回家过年了，以后再说，祝新年快乐啊！

**Comment by liyujiang-gzu** [comment]
1.5.X版本应该不存在此问题了
