### ISSUE TITLE
start月和end月是同一个月的话,endDay条件不起作用

### ISSUE THREAD

**Issue by ljf1172361058** [gzu-liyujiang/AndroidPicker#86]
我设置1月份为开始月 结束月也是1月份 然后结束日为24 发现开始月和结束月一样 我的结束日竟然是31
也就是说我的endDay条件没起作用(PS:开始月和结束月不一样的话就没问题)

**Comment by Tandrow** [comment]
你用的哪个版本的，这个问题似乎已经修改好了

**Comment by ljf1172361058** [comment]
准确的说应该是这样,假设1900/1/1为开始时间, 2017/2/7为结束时间,2000/1/1为默认选中的时间
此时我滑啊滑,滑到2005/2/20,此时天数为20,那么现在我把年份滚动到2017,会发现月份会刷新,这个没问题,但是发现日没变,也就是说我可以设置时间为2017/2/20日,突破了我的2017/2/7结束时间上限

**Comment by Tandrow** [comment]
soga，开始描述的和我之前一样，切换年份时好像只刷新了月份数据，才有这个问题出现，楼主有空就改改提交给作者吧

**Comment by liyujiang-gzu** [comment]
1.4.4已改
