### ISSUE TITLE
混淆之后，点击选择器程序崩溃

### ISSUE THREAD

**Issue by jimdaxu** [gzu-liyujiang/AndroidPicker#96]
![default](https://cloud.githubusercontent.com/assets/14083020/23396130/1200c20e-fdcd-11e6-89c7-15b908ae7d62.png)

不混淆的话，是正常的。

**Comment by liyujiang-gzu** [comment]
由于地址选择器使用了fastjson来解析，混淆时候需要加入以下类似的规则，不混淆Province、City等实体类。

-keepattributes InnerClasses,Signature
-keepattributes *Annotation*

-keep class cn.qqtheme.framework.entity.** { *;}

**Comment by jimdaxu** [comment]
混淆之后，可以正常使用了，谢谢。
